export const DEFAULT_WORK_PAGE_COPY = {
  openSchedule: "打开日程",
  viewTaskDetail: "查看任务详情",
  runPrefix: "运行",
  noRun: "暂无运行",
  duePrefix: "截止",
  interventionFocus: "当前重点",
  noBlockingAction: "当前没有记录阻塞动作。",
  plannedWindow: "计划时间窗",
  reliability: "同步状态",
  lastRefresh: "最近刷新",
  lastSync: "最近同步",
  stopReason: "停止原因",
  stuckFor: "停滞时长",
  staleSync: "同步已过期",
  healthySync: "同步正常",
  workbenchTitle: "给 Agent 补充要求",
  workbenchDescription: "补充约束、修改方向、指定输出格式，或提供缺失背景。",
  workbenchStatus: "下一步",
  conversationWorkbenchAria: "工作对话区",
  planRailAria: "任务计划侧栏",
  nextAction: "建议动作",
  whyNow: "为什么现在处理",
  evidence: "相关背景",
  taskArrangement: "给 Agent 补充要求",
  taskArrangementHint:
    "例如：先澄清任务目标，列出限制条件，并给我一版简短执行计划，输出用要点形式。",
  collaboration: "协作",
  agentMessage: "Agent 更新",
  conversationInput: "发送给 Agent 的内容",
  operatorNote: "人工备注",
  sendToAgent: "发送给 Agent",
  sendAndContinue: "启动并继续",
  sendNoteToAgent: "发送补充说明",
  resumeWithMessage: "带说明继续",
  currentRun: "当前运行",
  approve: "批准",
  reject: "拒绝",
  editedInstruction: "修改后的指令",
  editAndApprove: "修改后批准",
  retryPrompt: "重试提示词",
  retryRun: "重新执行",
  acceptResult: "确认结果",
  markTaskDone: "标记任务完成",
  createFollowUp: "创建后续任务",
  followUpTitle: "后续任务标题",
  followUpDue: "后续任务截止时间",
  reopenTask: "重新打开任务",
  latestFollowUp: "最新后续任务",
  resultAccepted: "结果已确认",
  taskDone: "任务已完成",
  continueRun: "继续下一轮执行",
  continueRunDescription:
    "这轮执行已经结束。先确认最新结果，再直接从这里继续下一轮，而不是切到新的流程里。",
  resultActionsTitle: "后续动作",
  followUpOptional: "可选：拆出后续任务",
  followUpOptionalDescription:
    "只有当这项工作真的需要拆成新轨道时，再创建后续任务。",
  runPrompt: "运行提示词",
  startRunHere: "立即启动",
  noActiveRunYet: "当前还没有活动运行",
  fallbackNoOperatorInput:
    "还没有任务记录。启动任务后，这里会按时间显示关键进展，例如开始执行、等待确认或产出更新。",
  fallbackStartFromTaskPage: "先启动运行，再从这里继续补充要求。",
  sharedOutput: "最新结果",
  sharedOutputDescription: "把最新可用结果放在工作区附近，避免你来回翻日志。",
  usedByNextAction: "下一步会用到",
  updated: "更新于",
  openArtifact: "打开产物",
  executionWorkstream: "任务记录",
  executionWorkstreamDescription:
    "背景记录默认收在这里；需要追查细节时再切换对话往来。",
  workstream: "任务记录",
  conversation: "对话往来",
  latestExecutionMilestones: "最近任务记录",
  conversationEvidence: "对话往来",
  conversationEvidenceDescription: "当里程碑摘要不够时，再展开查看完整对话。",
  composerRequired: "需要填写发送给 Agent 的内容",
  messageRequired: "消息不能为空",
  noteQueuedForCheckpoint: "消息会在下一个安全检查点送达，并在同步后显示。",
  responseRequiredDescription: "补充说明后，阻塞中的运行才能继续。",
  noteWhileRunningDescription:
    "运行进行中也可以补充背景，但不会强行打断当前执行。",
  noteWhileAwaitingApprovalDescription:
    "审批未完成前也可以补充背景，但运行仍会等待审批结果。",
  promptRequired: "提示词不能为空",
  noActiveRunToResume: "当前没有可继续的运行。",
  currentRunCannotAcceptMessages: "当前运行暂时不能接收人工消息。",
  actionFailed: "操作失败",
  keyboardHint: "Enter 提交 · Shift+Enter 换行",
  currentStage: "当前阶段",
  sourceSchedule: "来自日程",
  noScheduleWindow: "暂无计划时间窗",
  taskReadySummary:
    "任务还没有启动。现在最重要的是决定是否从这个工作台开始第一轮执行。",
  taskRunningSummary: "任务正在执行中。只有在需要纠偏或补充限制时再介入。",
  taskWaitingInputSummary: "Agent 正在等待你的补充说明，才能继续当前任务。",
  taskWaitingApprovalSummary: "Agent 正在等待你的决定，审批后才能继续。",
  taskCompletedSummary: "最新一轮已经完成。先确认结果，再决定是否继续推进。",
  taskAwaitingReviewLabel: "待确认",
  taskFailedSummary: "上一轮执行已中断。现在要决定是恢复、重试，还是改方向。",
  currentKeyDecision: "当前需要你决定",
  collaborationFlow: "对话记录",
  collaborationFlowDescription:
    "输入后，下面按时间顺序显示对话消息：Agent 在左，你在右。",
  conversationTab: "协作推进",
  fullFlowTab: "执行记录",
  workbenchViewTabs: "工作区视图切换",
  latestResult: "最新结果",
  inputArea: "输入区",
  quickPrompts: "快捷补充",
  newTask: "新建任务",
  workspaceViews: "工作区入口",
  allTasks: "任务列表",
  openInbox: "收件箱",
  openMemory: "记忆库",
  currentTask: "当前任务",
  taskStages: "任务状态",
  taskLifecycle: "任务生命周期",
  collaborationStage: "当前协作阶段",
  lifecycleNotStarted: "未开始",
  lifecycleInProgress: "进行中",
  lifecycleCompleted: "已完成",
  latestDecision: "最新决策",
  openWorkbench: "打开工作台",
  workbenchCrumb: "工作台",
  decisionStatus: "当前状态",
  decisionPlan: "启动后 Agent 会",
  decisionOptions: "你现在可以",
  modifyBeforeStart: "先补充说明再启动",
  adjustSchedule: "调整日程",
  notNow: "暂不处理",
  resultEmptyTitle: "尚未生成结果",
  resultEmptyDescription:
    "启动后，这里会优先显示 Agent 的第一轮理解、执行建议、草稿，或待你确认的问题。",
  resultPreviewTitle: "启动后，这里通常会显示：",
  resultPreviewUnderstanding: "第一轮任务理解",
  resultPreviewPlan: "执行建议",
  resultPreviewDraft: "草稿或摘要",
  resultPreviewQuestions: "待你确认的问题",
  secondaryActions: "次操作",
  decisionReminder: "补充提醒",
  milestoneWaitingStart: "等待你决定是否启动",
  taskShellAria: "任务概览",
  nextActionHeroAria: "当前重点区域",
  latestResultAria: "最新结果区域",
  executionStreamAria: "任务记录区域",
  workInspectorAria: "工作检查区",
  scheduleCrumb: "日程",
  currentBlocker: "当前阻塞",
  deadline: "截止时间",
  nextActionBadge: "当前重点",
  latestResultEyebrow: "最新结果",
  taskPlan: "任务计划",
  planReadySummary: "计划会随当前运行状态更新。",
  planEmptySummary: "生成后会在这里显示当前步骤与恢复入口。",
  noTaskPlan: "还没有任务计划",
  generatePlaceholderPlan: "生成占位计划",
  currentStep: "当前步骤",
  taskPath: "任务路径",
  upcomingSteps: "后续步骤",
  resumeFromPlan: "重新规划后继续",
  pendingApprovals: "待处理审批",
  noPendingApprovals: "当前没有待处理审批。",
  currentArtifacts: "当前产出",
  noArtifacts: "当前没有产出。",
  toolLog: "工具记录",
  noToolLog: "当前没有工具调用记录。",
  toolArguments: "参数",
  toolResult: "结果",
  toolError: "错误",
  taskContext: "任务背景",
  priorityLabel: "优先级",
  dueAtLabel: "截止时间",
  scheduledWindowLabel: "计划时间窗",
  scheduleStatusLabel: "日程状态",
  runStatusLabel: "运行状态",
  syncStatusLabel: "同步状态",
  lastUpdatedLabel: "最近更新",
  lastSyncedLabel: "最近同步",
  stopReasonLabel: "停止原因",
  invalidFollowUpDate: "后续任务截止时间无效",
  invalidFollowUpTitle: "后续任务标题不能为空",
  noValue: "暂无",
  pendingStep: "待开始",
  inProgressStep: "进行中",
  waitingForUserStep: "等待你确认",
  doneStep: "已完成",
  blockedStep: "阻塞",
  closureStatusTitle: "任务生命周期",
  closureAcceptedAt: "结果确认时间",
  closureDoneAt: "任务完成时间",
  latestFollowUpStatus: "任务状态",
  latestFollowUpSchedule: "日程状态",
  latestFollowUpCreatedAt: "创建时间",
  approvalSummaryFallback: "继续运行前，请先查看这条审批。",
  agentLabel: "智能体",
  followUpDefaultSuffix: "后续任务",
} as const;
