sonar.projectKey=saya-ashen_Chrona
sonar.organization=saya-ashen

sonar.exclusions=packages/db/src/generated/**,.specify/**,**/*.test.ts,**/*.test.tsx,**/*.bun.test.ts,external-plugins/**
sonar.cpd.exclusions=packages/db/src/generated/**,.specify/**,**/*.generated.*,**/__generated__/**,**/*.test.ts,**/*.test.tsx,**/*.bun.test.ts,external-plugins/**
sonar.coverage.exclusions=packages/db/src/generated/**,.specify/**,**/*.test.ts,**/*.test.tsx,**/*.bun.test.ts,external-plugins/**
