import {
  copyFileSync,
  existsSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { Database } from "bun:sqlite";

import { acquireSqliteRuntimeLock, type SqliteRuntimeLock } from "./sqlite-runtime-lock";
import { ensurePrivateDirectory, secureGeneratedPrivateFile, sqlitePathFromFileUrl } from "./sqlite-url";

const AUTOMATIC_BACKUP_RETENTION = 5;
const RESTORE_MARKER_VERSION = 1;

export type SqliteBackupResult = {
  sourcePath: string;
  backupPath: string;
};

export type PreUpgradeBackupResult = SqliteBackupResult & {
  metadataPath: string;
  sourceFingerprint: string;
  targetReleaseLine: string;
};

type RestoreMarker = {
  version: number;
  activePath: string;
  recoveryPath: string | null;
  retiredPath: string | null;
  stagedPath: string | null;
  phase: "staged" | "prior_retired" | "replaced";
};

type RestoreOptions = {
  force?: boolean;
  /** Test seam for replacement failures; production uses renameSync. */
  rename?: (from: string, to: string) => void;
  /** Test seam for interruption after old WAL sidecars are retired. */
  onSidecarsRemoved?: () => void;
};

function requireFilePath(databaseUrl: string): string {
  const sqlitePath = sqlitePathFromFileUrl(databaseUrl);
  if (!sqlitePath || sqlitePath === ":memory:") {
    throw new Error("Chrona backup requires a persistent SQLite file.");
  }
  return resolve(sqlitePath);
}

function quoteSqliteLiteral(value: string): string {
  return value.replaceAll("'", "''");
}

export function assertHealthySqliteDatabase(databasePath: string): void {
  const db = new Database(databasePath, { readonly: true });
  try {
    const result = db.query("PRAGMA quick_check").get() as { quick_check?: string } | null;
    if (result?.quick_check !== "ok") {
      throw new Error("SQLite integrity check failed for the requested database.");
    }
  } finally {
    db.close();
  }
}

/** Creates a missing Chrona directory without changing an existing parent. */
function createPrivateDirectory(path: string): void {
  // Existing selected directories are audited rather than rewritten.
  ensurePrivateDirectory(path);
}

/** Files at these paths are generated by Chrona, never arbitrary user files. */
function secureGeneratedFile(path: string): void {
  secureGeneratedPrivateFile(path);
}

function vacuumInto(sourcePath: string, destinationPath: string): void {
  const db = new Database(sourcePath);
  try {
    db.run(`VACUUM INTO '${quoteSqliteLiteral(destinationPath)}'`);
  } finally {
    db.close();
  }
  assertHealthySqliteDatabase(destinationPath);
  secureGeneratedFile(destinationPath);
}

export function backupSqliteDatabase(databaseUrl: string, outputPath: string): SqliteBackupResult {
  const sourcePath = requireFilePath(databaseUrl);
  const backupPath = resolve(outputPath);
  if (!existsSync(sourcePath)) {
    throw new Error("Chrona database was not found for backup.");
  }
  if (sourcePath === backupPath) {
    throw new Error("Backup destination must differ from the active Chrona database.");
  }

  createPrivateDirectory(dirname(backupPath));
  vacuumInto(sourcePath, backupPath);
  return { sourcePath, backupPath };
}

function timestamp(): string {
  return new Date().toISOString().replaceAll(/[:.]/g, "-");
}

function automaticBackupDirectory(databasePath: string): string {
  return join(dirname(databasePath), "backups", "pre-upgrade");
}

function trimAutomaticBackups(directory: string, keepPath: string): void {
  const entries = Bun.file(directory);
  void entries;
  // Bun's glob is unnecessary here; readdir avoids treating user-controlled names as paths.
  const names = Array.from(new Bun.Glob("*.sqlite").scanSync({ cwd: directory }))
    .map((name) => join(directory, name))
    .filter((path) => path !== keepPath)
    .sort((left, right) => statSync(right).mtimeMs - statSync(left).mtimeMs);
  for (const path of names.slice(Math.max(0, AUTOMATIC_BACKUP_RETENTION - 1))) {
    rmSync(path, { force: true });
    rmSync(`${path}.json`, { force: true });
  }
}

/** Creates a validated automatic recovery point before a schema/history upgrade. */
export function createPreUpgradeBackup(input: {
  databaseUrl: string;
  sourceFingerprint: string;
  targetReleaseLine: string;
}): PreUpgradeBackupResult {
  const sourcePath = requireFilePath(input.databaseUrl);
  if (!existsSync(sourcePath)) throw new Error("Chrona database was not found for upgrade backup.");
  const directory = automaticBackupDirectory(sourcePath);
  createPrivateDirectory(directory);
  const backupPath = join(directory, `${basename(sourcePath, ".db")}-${timestamp()}-${input.targetReleaseLine}.sqlite`);
  const result = backupSqliteDatabase(input.databaseUrl, backupPath);
  const metadataPath = `${backupPath}.json`;
  writeFileSync(metadataPath, `${JSON.stringify({
    createdAt: new Date().toISOString(),
    sourceFingerprint: input.sourceFingerprint,
    sourceName: basename(sourcePath),
    targetReleaseLine: input.targetReleaseLine,
  })}\n`, { mode: 0o600 });
  secureGeneratedFile(metadataPath);
  trimAutomaticBackups(directory, backupPath);
  return { ...result, metadataPath, sourceFingerprint: input.sourceFingerprint, targetReleaseLine: input.targetReleaseLine };
}

function restoreMarkerPath(databasePath: string): string {
  return `${databasePath}.restore.json`;
}

function writeRestoreMarker(databasePath: string, marker: RestoreMarker): void {
  const markerPath = restoreMarkerPath(databasePath);
  writeFileSync(markerPath, `${JSON.stringify(marker)}\n`, { mode: 0o600 });
  secureGeneratedFile(markerPath);
}

function readRestoreMarker(databasePath: string): RestoreMarker | null {
  const markerPath = restoreMarkerPath(databasePath);
  if (!existsSync(markerPath)) return null;
  try {
    const marker = JSON.parse(readFileSync(markerPath, "utf8")) as Partial<RestoreMarker>;
    if (
      marker.version === RESTORE_MARKER_VERSION
      && marker.activePath === databasePath
      && ["staged", "prior_retired", "replaced"].includes(marker.phase ?? "")
    ) {
      return marker as RestoreMarker;
    }
  } catch {
    // Invalid marker is not safe to ignore: it may represent an interrupted replacement.
  }
  throw new Error("Chrona found an unreadable restore recovery marker; inspect the data directory before retrying.");
}

function restoreVerifiedRecoverySnapshot(databasePath: string, marker: RestoreMarker): void {
  if (!marker.recoveryPath || !existsSync(marker.recoveryPath)) {
    throw new Error("Chrona restore recovery cannot find the verified pre-restore database.");
  }
  if (existsSync(databasePath)) {
    // Preserve the uncertain main file before removing sidecars or replacing it.
    renameSync(databasePath, `${databasePath}.restore-interrupted-${process.pid}-${Date.now()}`);
  }
  removeSqliteSidecars(databasePath);
  const recoveryStage = `${databasePath}.restore-recovery-${process.pid}-${Date.now()}`;
  copyFileSync(marker.recoveryPath, recoveryStage);
  assertHealthySqliteDatabase(recoveryStage);
  renameSync(recoveryStage, databasePath);
}

/** Repairs an interrupted restore without accepting a main DB separated from its WAL. */
export function recoverInterruptedSqliteRestore(databaseUrl: string): void {
  const databasePath = requireFilePath(databaseUrl);
  const marker = readRestoreMarker(databasePath);
  if (!marker) return;

  // Once the old main file was retired, a replacement may be incomplete or a
  // rollback may have restored a main file after its WAL was removed. The
  // verified recovery snapshot is authoritative in either case.
  if (marker.phase === "prior_retired") {
    restoreVerifiedRecoverySnapshot(databasePath, marker);
  } else if (!existsSync(databasePath)) {
    if (marker.recoveryPath && existsSync(marker.recoveryPath)) {
      restoreVerifiedRecoverySnapshot(databasePath, marker);
    } else if (marker.retiredPath && existsSync(marker.retiredPath)) {
      renameSync(marker.retiredPath, databasePath);
    } else {
      throw new Error("Chrona restore recovery cannot find either the active or preserved database.");
    }
  }

  assertHealthySqliteDatabase(databasePath);
  if (marker.stagedPath && existsSync(marker.stagedPath)) rmSync(marker.stagedPath, { force: true });
  rmSync(restoreMarkerPath(databasePath), { force: true });
}

function removeSqliteSidecars(databasePath: string): void {
  rmSync(`${databasePath}-wal`, { force: true });
  rmSync(`${databasePath}-shm`, { force: true });
}

type PreparedRestore = {
  databasePath: string;
  marker: RestoreMarker;
  recoveryPath: string | null;
  retiredPath: string | null;
  sourcePath: string;
  stagedPath: string;
};

function prepareRestore(
  lock: SqliteRuntimeLock,
  databaseUrl: string,
  inputPath: string,
  force: boolean | undefined,
): PreparedRestore {
  const sourcePath = resolve(inputPath);
  const databasePath = lock.databasePath;
  if (!existsSync(sourcePath)) throw new Error("Chrona restore source database was not found.");
  if (sourcePath === databasePath) throw new Error("Restore source must differ from the active Chrona database.");
  recoverInterruptedSqliteRestore(databaseUrl);
  if (existsSync(databasePath) && !force) throw new Error("Chrona database already exists. Pass --force to replace it.");
  assertHealthySqliteDatabase(sourcePath);
  createPrivateDirectory(dirname(databasePath));
  const unique = `${process.pid}-${Date.now()}`;
  const stagedPath = `${databasePath}.restore-stage-${unique}`;
  const hasCurrentDatabase = existsSync(databasePath);
  const retiredPath = hasCurrentDatabase ? `${databasePath}.pre-restore-${unique}` : null;
  const recoveryPath = hasCurrentDatabase ? `${databasePath}.pre-restore-${unique}.sqlite` : null;
  return {
    databasePath,
    sourcePath,
    stagedPath,
    retiredPath,
    recoveryPath,
    marker: { version: RESTORE_MARKER_VERSION, activePath: databasePath, recoveryPath, retiredPath, stagedPath, phase: "staged" },
  };
}

function stageRestore(prepared: PreparedRestore): void {
  copyFileSync(prepared.sourcePath, prepared.stagedPath);
  assertHealthySqliteDatabase(prepared.stagedPath);
  secureGeneratedFile(prepared.stagedPath);
  if (prepared.recoveryPath) vacuumInto(prepared.databasePath, prepared.recoveryPath);
  writeRestoreMarker(prepared.databasePath, prepared.marker);
}

function rollbackRetiredDatabase(prepared: PreparedRestore, rename: (from: string, to: string) => void): void {
  if (existsSync(prepared.databasePath) || !prepared.retiredPath || !existsSync(prepared.retiredPath)) return;
  try {
    rename(prepared.retiredPath, prepared.databasePath);
  } catch {
    // The durable marker makes the next start/restore repair this state.
  }
}

function replaceStagedDatabase(
  prepared: PreparedRestore,
  rename: (from: string, to: string) => void,
  onSidecarsRemoved: (() => void) | undefined,
): void {
  if (prepared.retiredPath) {
    // Retire the main database before removing its WAL sidecars. If anything
    // interrupts after this point, the marker makes the verified WAL-aware
    // recovery snapshot authoritative rather than accepting a stale main file.
    rename(prepared.databasePath, prepared.retiredPath);
    prepared.marker = { ...prepared.marker, phase: "prior_retired" };
    writeRestoreMarker(prepared.databasePath, prepared.marker);
  }
  removeSqliteSidecars(prepared.databasePath);
  onSidecarsRemoved?.();
  rename(prepared.stagedPath, prepared.databasePath);
  prepared.marker = { ...prepared.marker, phase: "replaced", stagedPath: null };
  writeRestoreMarker(prepared.databasePath, prepared.marker);
  assertHealthySqliteDatabase(prepared.databasePath);
  rmSync(restoreMarkerPath(prepared.databasePath), { force: true });
}

function restoreWithLock(
  lock: SqliteRuntimeLock,
  databaseUrl: string,
  inputPath: string,
  options: RestoreOptions,
): SqliteBackupResult & { recoveryPath: string | null } {
  const prepared = prepareRestore(lock, databaseUrl, inputPath, options.force);
  const rename = options.rename ?? renameSync;
  try {
    stageRestore(prepared);
    replaceStagedDatabase(prepared, rename, options.onSidecarsRemoved);
  } catch (error) {
    rollbackRetiredDatabase(prepared, rename);
    throw error;
  }
  return { sourcePath: prepared.sourcePath, backupPath: prepared.databasePath, recoveryPath: prepared.recoveryPath };
}

export function restoreSqliteDatabase(
  databaseUrl: string,
  inputPath: string,
  options: RestoreOptions = {},
): SqliteBackupResult & { recoveryPath: string | null } {
  const lock = acquireSqliteRuntimeLock(databaseUrl);
  try {
    return restoreWithLock(lock, databaseUrl, inputPath, options);
  } finally {
    lock.release();
  }
}
