import { chmodSync, existsSync, mkdirSync } from "node:fs";
import { assertWindowsPrivateStorage, ensureWindowsPrivateDirectory, secureWindowsGeneratedStorage } from "./windows-private-storage";
import { basename, dirname, resolve, sep } from "node:path";

const DEFAULT_DEV_DATABASE_URL = "file:./prisma/dev.db";
const DEFAULT_TEST_DATABASE_URL = "file:./.tmp/bun-test.db";
export const AUTO_TEST_DATABASE_ENV = "CHRONA_AUTO_TEST_DATABASE_URL";

export function resolveRuntimeDatabaseUrl(env: NodeJS.ProcessEnv): string {
  if (env.NODE_ENV === "test") {
    const databaseUrl = env.DATABASE_URL ?? DEFAULT_TEST_DATABASE_URL;
    assertSafeTestDatabaseUrl(databaseUrl);
    if (!env.DATABASE_URL) {
      env[AUTO_TEST_DATABASE_ENV] = "1";
    }
    env.DATABASE_URL = databaseUrl;
    return databaseUrl;
  }

  if (env.DATABASE_URL) {
    return env.DATABASE_URL;
  }

  return DEFAULT_DEV_DATABASE_URL;
}

export function isSafeTestDatabaseUrl(databaseUrl: string | undefined, cwd = process.cwd()): boolean {
  const sqlitePath = sqlitePathFromFileUrl(databaseUrl ?? "");
  if (!sqlitePath) {
    return false;
  }

  if (sqlitePath === ":memory:") {
    return true;
  }

  const absolutePath = resolve(cwd, sqlitePath);
  const segments = absolutePath.split(sep).map((segment) => segment.toLowerCase());
  const filename = basename(absolutePath).toLowerCase();

  return segments.includes(".tmp") || filename.includes("test");
}

export function assertSafeTestDatabaseUrl(databaseUrl: string | undefined): void {
  if (isSafeTestDatabaseUrl(databaseUrl)) {
    return;
  }

  throw new Error(
    [
      "Refusing to use DATABASE_URL for tests because it does not point to an isolated test SQLite database.",
      `Current DATABASE_URL: ${databaseUrl ?? "(unset)"}`,
      `Use ${DEFAULT_TEST_DATABASE_URL}, an in-memory database, or another path under .tmp / containing test.`,
    ].join(" "),
  );
}

export function resolveSqliteAdapterUrl(url: string): string {
  const sqlitePath = sqlitePathFromFileUrl(url);
  if (!sqlitePath || sqlitePath === ":memory:") {
    return url;
  }
  // prisma-adapter-bun-sqlite treats everything after `file:` as a filesystem
  // path, unlike migration/backup helpers. Drop URL query parameters so every
  // database operation targets the same SQLite file.
  return `file:${sqlitePath}`;
}

export function isInMemorySqliteUrl(databaseUrl: string): boolean {
  return databaseUrl === "file::memory:" || databaseUrl === ":memory:";
}

export function sqlitePathFromFileUrl(databaseUrl: string): string | null {
  if (isInMemorySqliteUrl(databaseUrl)) {
    return ":memory:";
  }

  if (!databaseUrl.startsWith("file:")) {
    return null;
  }

  const pathWithParams = databaseUrl.slice("file:".length);
  const queryIndex = pathWithParams.indexOf("?");
  return queryIndex >= 0 ? pathWithParams.slice(0, queryIndex) : pathWithParams;
}

export function assertSqliteFileUrl(databaseUrl: string): void {
  if (sqlitePathFromFileUrl(databaseUrl)) {
    return;
  }

  throw new Error(`Chrona requires a SQLite file URL, got: ${databaseUrl}`);
}

/** Windows private storage is applied and audited with built-in PowerShell and icacls. */
export function assertPrivateStorageSupported(): void {
  // Kept as a compatibility boundary for callers. Windows support is verified
  // when a concrete Chrona-owned path is created or audited below.
}

/** Secure a file generated by Chrona without touching arbitrary user files. */
export function secureGeneratedPrivateFile(path: string): void {
  if (process.platform === "win32") {
    secureWindowsGeneratedStorage(path, false);
  } else {
    chmodSync(path, 0o600);
  }
}

/** Secure SQLite WAL/SHM files generated after the runtime adapter opens. */
export function secureGeneratedSqliteSidecars(databaseUrl: string): void {
  const sqlitePath = sqlitePathFromFileUrl(databaseUrl);
  if (!sqlitePath || sqlitePath === ":memory:") return;
  for (const suffix of ["-wal", "-shm"]) {
    const artifactPath = `${resolve(sqlitePath)}${suffix}`;
    if (existsSync(artifactPath)) secureGeneratedPrivateFile(artifactPath);
  }
}

/** Create a Chrona-owned directory, or audit an existing selected directory. */
export function ensurePrivateDirectory(path: string): void {
  if (process.platform === "win32") {
    ensureWindowsPrivateDirectory(path);
    return;
  }
  const existed = existsSync(path);
  mkdirSync(path, { recursive: true, mode: 0o700 });
  // Preserve an existing user-selected POSIX directory mode by design.
  void existed;
}

/** Audit a storage path without mutating it. */
export function assertPrivateStoragePath(path: string): void {
  if (process.platform === "win32") assertWindowsPrivateStorage(path);
}

/** Creates a missing SQLite parent privately without changing an existing parent. */
export function ensureSqliteParentDir(databaseUrl: string): void {
  const sqlitePath = sqlitePathFromFileUrl(databaseUrl);
  if (!sqlitePath || sqlitePath === ":memory:") {
    return;
  }

  assertPrivateStorageSupported();
  // `mode` applies only to directories created by this call (and can only be
  // narrowed by umask). Windows audits an existing selected parent instead of
  // silently rewriting it.
  ensurePrivateDirectory(dirname(resolve(sqlitePath)));
}
