export const DEFAULT_WORK_PAGE_COPY = {
  openSchedule: "Open Schedule",
  viewTaskDetail: "View task detail",
  runPrefix: "Run",
  noRun: "No run",
  duePrefix: "Due",
  interventionFocus: "Current focus",
  noBlockingAction: "No blocking action recorded.",
  plannedWindow: "Planned window",
  reliability: "Sync status",
  lastRefresh: "Last refresh",
  lastSync: "Last sync",
  stopReason: "Stop reason",
  stuckFor: "Stuck for",
  staleSync: "Sync stale",
  healthySync: "Sync healthy",
  workbenchTitle: "Add requirements for Agent",
  workbenchDescription: "Add constraints, change direction, specify output format, or provide missing context.",
  workbenchStatus: "Next step",
  conversationWorkbenchAria: "Work conversation area",
  planRailAria: "Task plan sidebar",
  nextAction: "Suggested action",
  whyNow: "Why now",
  evidence: "Related context",
  taskArrangement: "Add requirements for Agent",
  taskArrangementHint:
    "E.g.: First clarify the task objective, list constraints, then give me a brief execution plan in bullet points.",
  collaboration: "Collaboration",
  agentMessage: "Agent update",
  conversationInput: "Message to Agent",
  operatorNote: "Operator note",
  sendToAgent: "Send to Agent",
  sendAndContinue: "Start and continue",
  sendNoteToAgent: "Send supplementary note",
  resumeWithMessage: "Resume with note",
  currentRun: "Current run",
  approve: "Approve",
  reject: "Reject",
  editedInstruction: "Edited instruction",
  editAndApprove: "Edit and approve",
  retryPrompt: "Retry prompt",
  retryRun: "Retry run",
  acceptResult: "Accept result",
  markTaskDone: "Mark task done",
  createFollowUp: "Create follow-up task",
  followUpTitle: "Follow-up title",
  followUpDue: "Follow-up due date",
  reopenTask: "Reopen task",
  latestFollowUp: "Latest follow-up",
  resultAccepted: "Result accepted",
  taskDone: "Task completed",
  continueRun: "Continue next run",
  continueRunDescription:
    "This run has finished. Review the latest result first, then continue the next run directly from here instead of switching to a new flow.",
  resultActionsTitle: "Follow-up actions",
  followUpOptional: "Optional: split into follow-up task",
  followUpOptionalDescription:
    "Only create a follow-up task when the work truly needs to split into a new track.",
  runPrompt: "Run prompt",
  startRunHere: "Start now",
  noActiveRunYet: "No active run yet",
  fallbackNoOperatorInput:
    "No task records yet. After starting, key milestones such as execution start, waiting for confirmation, or output updates will appear here in chronological order.",
  fallbackStartFromTaskPage: "Start a run first, then add requirements from here.",
  sharedOutput: "Latest result",
  sharedOutputDescription: "Keep the latest available result near the work area so you don't have to scroll through logs.",
  usedByNextAction: "Used by next action",
  updated: "Updated",
  openArtifact: "Open artifact",
  executionWorkstream: "Task record",
  executionWorkstreamDescription:
    "Background records are collapsed here by default; switch to conversation view when you need to trace details.",
  workstream: "Task record",
  conversation: "Conversation",
  latestExecutionMilestones: "Recent task records",
  executionRecordMain: "Execution record main area",
  executionRecordSidebar: "Execution record sidebar",
  taskCockpit: "Task cockpit",
  taskCockpitDescription: "Pin current blockers, suggested actions, recent output, and risks in the sidebar to avoid scrolling through the execution stream.",
  executionSnapshot: "Pinned summary",
  executionSnapshotDescription: "Pin key information needed to assess task status in the sidebar, separate from the event stream.",
  latestEvent: "Latest event",
  currentFocusSummary: "Current focus",
  recentOutput: "Recent output",
  riskAndSync: "Risk & sync",
  noRecentOutput: "No output available yet.",
  noSuggestedAction: "No extra actions right now, continue observing execution.",
  conversationEvidence: "Conversation",
  conversationEvidenceDescription: "Expand the full conversation when milestone summaries aren't enough.",
  composerRequired: "Message to Agent is required",
  messageRequired: "Message cannot be empty",
  noteQueuedForCheckpoint: "Message will be delivered at the next safe checkpoint and displayed after sync.",
  responseRequiredDescription: "The blocked run can only continue after you provide additional input.",
  noteWhileRunningDescription:
    "You can add context while the run is in progress, but it won't forcefully interrupt the current execution.",
  noteWhileAwaitingApprovalDescription:
    "You can add context before approval is complete, but the run will still wait for the approval result.",
  promptRequired: "Prompt cannot be empty",
  noActiveRunToResume: "No run available to resume.",
  currentRunCannotAcceptMessages: "The current run cannot accept operator messages right now.",
  actionFailed: "Action failed",
  keyboardHint: "Enter to submit · Shift+Enter for new line",
  currentStage: "Current stage",
  sourceSchedule: "From schedule",
  noScheduleWindow: "No planned window",
  taskReadySummary:
    "Task has not started yet. The most important decision now is whether to start the first run from this workbench.",
  taskRunningSummary: "Task is running. Only intervene when you need to correct course or add constraints.",
  taskWaitingInputSummary: "Agent is waiting for your additional input before continuing.",
  taskWaitingApprovalSummary: "Agent is waiting for your decision; approval is needed before continuing.",
  taskCompletedSummary: "The latest round is complete. Review the result first, then decide whether to continue.",
  taskAwaitingReviewLabel: "Awaiting review",
  taskFailedSummary: "The last run was interrupted. Decide now whether to recover, retry, or change direction.",
  currentKeyDecision: "Your decision is needed",
  collaborationFlow: "Conversation log",
  collaborationFlowDescription:
    "After input, messages appear in chronological order below: Agent on the left, you on the right.",
  conversationTab: "Collaborative progress",
  fullFlowTab: "Execution record",
  workbenchViewTabs: "Workspace view tabs",
  latestResult: "Latest result",
  inputArea: "Input area",
  quickPrompts: "Quick prompts",
  newTask: "New task",
  workspaceViews: "Workspace views",
  allTasks: "Task list",
  openInbox: "Inbox",
  openMemory: "Memory",
  currentTask: "Current task",
  taskStages: "Task status",
  taskLifecycle: "Task lifecycle",
  collaborationStage: "Current collaboration stage",
  lifecycleNotStarted: "Not started",
  lifecycleInProgress: "In progress",
  lifecycleCompleted: "Completed",
  latestDecision: "Latest decision",
  openWorkbench: "Open workbench",
  workbenchCrumb: "Workbench",
  decisionStatus: "Current status",
  decisionPlan: "After starting, Agent will",
  decisionOptions: "You can now",
  modifyBeforeStart: "Add notes before starting",
  adjustSchedule: "Adjust schedule",
  notNow: "Not now",
  resultEmptyTitle: "No result generated yet",
  resultEmptyDescription:
    "After starting, this area will show the Agent's first-round understanding, execution suggestions, drafts, or questions for your confirmation.",
  resultPreviewTitle: "After starting, this area typically shows:",
  resultPreviewUnderstanding: "First-round task understanding",
  resultPreviewPlan: "Execution suggestions",
  resultPreviewDraft: "Draft or summary",
  resultPreviewQuestions: "Questions for your confirmation",
  secondaryActions: "Secondary actions",
  decisionReminder: "Supplementary reminder",
  milestoneWaitingStart: "Waiting for your decision to start",
  taskShellAria: "Task overview",
  nextActionHeroAria: "Current focus area",
  latestResultAria: "Latest result area",
  executionStreamAria: "Task record area",
  workInspectorAria: "Work inspector",
  scheduleCrumb: "Schedule",
  currentBlocker: "Current blocker",
  deadline: "Deadline",
  nextActionBadge: "Current focus",
  latestResultEyebrow: "Latest result",
  taskPlan: "Task plan",
  planReadySummary: "The plan updates with the current run status.",
  planEmptySummary: "After acceptance, the plan graph will show the current and next nodes here.",
  noTaskPlan: "No task plan yet",
  currentStep: "Current step",
  taskPath: "Task path",
  upcomingSteps: "Upcoming steps",
  pendingApprovals: "Pending approvals",
  noPendingApprovals: "No pending approvals.",
  currentArtifacts: "Current artifacts",
  noArtifacts: "No artifacts.",
  toolLog: "Tool log",
  noToolLog: "No tool call records.",
  toolArguments: "Arguments",
  toolResult: "Result",
  toolError: "Error",
  taskContext: "Task context",
  priorityLabel: "Priority",
  dueAtLabel: "Due date",
  scheduledWindowLabel: "Planned window",
  scheduleStatusLabel: "Schedule status",
  runStatusLabel: "Run status",
  syncStatusLabel: "Sync status",
  lastUpdatedLabel: "Last updated",
  lastSyncedLabel: "Last synced",
  stopReasonLabel: "Stop reason",
  invalidFollowUpDate: "Invalid follow-up due date",
  invalidFollowUpTitle: "Follow-up title cannot be empty",
  noValue: "N/A",
  pendingStep: "Pending",
  inProgressStep: "In progress",
  waitingForUserStep: "Waiting for you",
  doneStep: "Done",
  blockedStep: "Blocked",
  skippedStep: "Skipped",
  waitingForChildStep: "Waiting for child",
  waitingForApprovalStep: "Waiting for approval",
  closureStatusTitle: "Task lifecycle",
  closureAcceptedAt: "Result accepted at",
  closureDoneAt: "Task completed at",
  latestFollowUpStatus: "Task status",
  latestFollowUpSchedule: "Schedule status",
  latestFollowUpCreatedAt: "Created at",
  approvalSummaryFallback: "Please review this approval before the run can continue.",
  agentLabel: "Agent",
  followUpDefaultSuffix: "follow-up",
  actionCurrentAction: "Current action",
  actionInputTitle: "Input needed",
  actionApprovalTitle: "Approval focus",
  actionRetryTitle: "Recovery suggestion",
  actionReviewTitle: "Review this round's output",
  actionObserveTitle: "Current collaboration mode",
  actionDefaultTitle: "Current action description",
  statusCompleted: "Completed",
  statusNotStarted: "Not started",
  statusInterrupted: "Interrupted",
  statusInProgress: "In progress",
  syncException: "Sync exception, awaiting recovery",
  waitingForApproval: "Waiting for approval",
  waitingForInput: "Waiting for additional input",
  executionInterrupted: "Execution interrupted, awaiting recovery",
  overdueSchedule: "Past the planned time window",
  quickPromptInputA: "Answer the missing information directly",
  quickPromptInputB: "State immutable constraints first",
  quickPromptInputC: "Flag any assumptions",
  quickPromptApprovalA: "Explain why this approach",
  quickPromptApprovalB: "Suggest a safer alternative",
  quickPromptApprovalC: "Summarize next steps after approval",
  quickPromptRetryA: "Identify the failure cause first",
  quickPromptRetryB: "Propose a recovery plan",
  quickPromptRetryC: "Narrow the scope of this change",
  quickPromptReviewA: "Summarize this round's output first",
  quickPromptReviewB: "Point out uncovered risks",
  quickPromptReviewC: "Suggest next steps",
  quickPromptObserveA: "Only add essential context",
  quickPromptObserveB: "Keep output concise",
  quickPromptObserveC: "Highlight any risks found",
  quickPromptStartA: "Give a concise plan first",
  quickPromptStartB: "State key assumptions",
  quickPromptStartC: "Ask clarifying questions first",
  quickPromptRunningA: "Only add essential context",
  quickPromptRunningB: "Keep output concise",
  quickPromptRunningC: "Highlight any risks found",
  quickPromptWaitingApprovalA: "Explain the current blocker",
  quickPromptWaitingApprovalB: "Suggest a safer change",
  quickPromptWaitingApprovalC: "Summarize the next steps",
  quickPromptDefaultA: "Continue based on latest results",
  quickPromptDefaultB: "Tighten the next action",
  quickPromptDefaultC: "Record this decision",
  planActionStart: "Start from this step",
  planActionApproval: "Handle current approval",
  planActionInput: "Continue after providing input",
  planActionRunning: "View current progress",
  planActionCompleted: "Confirm result",
  planActionRecover: "Recover from this step",
  planActionDefault: "View current action",
  userLabel: "You",
  continueProcessingPrefix: "Continue: ",
  recoverTaskPrefix: "Recover task: ",

  // ── Execution orchestration terminology ──
  workBlockLabel: "Work block",
  workBlockScheduled: "Scheduled",
  workBlockActive: "Active",
  workBlockCompleted: "Completed",
  workBlockCancelled: "Cancelled",
  noWorkBlock: "No work block",
  blockReasonLabel: "Block reason",
  blockReasonNeedsUserInput: "Needs your input",
  blockReasonNeedsApproval: "Needs approval",
  blockReasonExternalDependency: "External dependency",
  blockReasonMissingInfo: "Missing required information",
  blockReasonProviderUnavailable: "Provider unavailable",

  executionSessionLabel: "Execution session",
  executionSessionActive: "Active session",
  executionSessionPaused: "Paused",
  executionSessionCompleted: "Session complete",
  sessionStartCauseLabel: "Start cause",
  sessionStartScheduled: "Started from schedule",
  sessionStartManual: "Started manually",
  sessionPauseReasonLabel: "Pause reason",
  sessionCurrentStep: "Current step",
  sessionCompletedSteps: "Completed steps",
  sessionResumeAction: "Resume",
  sessionRestoreAction: "Restore from saved",
  sessionNotFound: "No active or paused execution session",

  planStepReadinessLabel: "Readiness",
  planStepReady: "Ready",
  planStepBlocked: "Blocked",
  planStepWaiting: "Waiting",
  planStepExecutionClassLabel: "Execution type",
  planStepExecutionClassAutoChain: "Automatic (chainable)",
  planStepExecutionClassAutoStandalone: "Automatic (standalone)",
  planStepExecutionClassHumanDependent: "Requires you",
  planStepExecutionClassReviewGate: "Review required",

  planStepDependenciesLabel: "Dependencies",
  planStepNoDependencies: "No dependencies",
  planStepRequiredInfoLabel: "Required information",
  planStepNoRequiredInfo: "No info required",

  nextActionLabel: "Next action",
  nextActionAutoStart: "Ready to auto-start",
  nextActionBlocked: "Blocked — resolve dependencies first",

  reviewOutcomeLabel: "Review outcome",
  reviewAccept: "Accepted",
  reviewReject: "Rejected",
  reviewRequestChanges: "Changes requested",
  reviewFeedbackLabel: "Review feedback",
  reviewNoFeedback: "No feedback given",
  reviewSubmitAction: "Submit review",
  reviewPendingLabel: "Awaiting review",

  resumeFromStep: "Resume from step",
  resumeWithInput: "Resume with input",
  resumeWithoutInput: "Resume without input",
  resumeInputPrompt: "What information should be provided to continue?",
  resumeInputRequired: "Input is required to continue this step",

  scheduleWorkBlockAction: "Schedule work block",
  unscheduleWorkBlockAction: "Remove from schedule",
  startWorkBlockNowAction: "Start now",
  startWorkBlockFromPlanAction: "Start from plan",

  planExecutionTimelineTitle: "Execution timeline",
  planExecutionTimelineEmpty: "No execution events yet",
  planExecutionAutoAdvance: "Auto-advancing eligible steps",
  planExecutionPausedAt: "Paused at step",
  planExecutionStoppedAt: "Stopped at step",
  planExecutionResumedAt: "Resumed at step",
} as const;
