import { Link } from "react-router-dom";
import { FileText, Folder, FolderPlus, Layers, MoreHorizontal, Plus, Settings2 } from "lucide-react";
import { localizeHref, useI18n } from "@chrona/i18n";
import { Button, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@shared/ui";
import type { LibraryFolder, LibraryGroup, LibraryItem, LibraryView } from "@chrona/contracts";
import type { LibraryLocation } from "../model/library-location";
import type { LibraryEditor } from "../model/library-editor";
import { libraryHref } from "../model/library-client";
import { libraryHeading } from "../model/library-heading";
export function LibraryHeader({ data, location, create }: { data: LibraryView | null; location: LibraryLocation; create: () => void }) {
  const { messages, locale } = useI18n(), c = messages.library;
  const { group, folder, title, count } = libraryHeading(data, location, c);
  return <header className="space-y-4"><nav aria-label={c.location} className="flex flex-wrap gap-2 text-sm text-muted-foreground"><Link to={localizeHref(locale,"/home")}>{c.all}</Link>{group && <><span>/</span><Link to={localizeHref(locale,libraryHref(group.id))}>{group.name}</Link></>}{(folder || location.unclassified) && <><span>/</span><span>{title}</span></>}</nav><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 space-y-2"><h1 className="break-words text-3xl font-semibold tracking-tight">{title}</h1><p className="text-sm text-muted-foreground">{c.total}：{count ?? "—"}</p></div><Button onClick={create}><Plus className="size-4" />{messages.workPages.newPage}</Button></div></header>;
}
export function LibraryToolbar({ data, location, search, chooseGroup, edit }: { data: LibraryView | null; location: LibraryLocation; search: (v: string) => void; chooseGroup: (id: string) => void; edit: (e: LibraryEditor) => void }) {
  const { messages } = useI18n(), c = messages.library, group = data?.groups.find(g=>g.id===location.groupId);
  return <div className="flex flex-wrap items-center gap-3"><Input className="min-w-0 flex-1 sm:max-w-sm" aria-label={location.groupId ? c.searchHere : c.search} placeholder={location.groupId ? c.searchHere : c.search} maxLength={200} value={location.query} onChange={e=>search(e.target.value)} /><Select value={location.groupId ?? "all"} onValueChange={chooseGroup}><SelectTrigger aria-label={c.classifyBy} className="min-w-0 max-w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{c.all}</SelectItem>{data?.groups.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select>{data?.canConfigure && <Button variant="outline" onClick={()=>edit({ kind: "group", group })}><Settings2 className="size-4" />{group ? c.manageGroup : c.newGroup}</Button>}</div>;
}
export function LibraryGroups({ groups }: { groups: LibraryGroup[] }) {
  const { messages, locale } = useI18n(), c = messages.library;
  return <section className="space-y-3"><h2 className="text-sm font-medium text-muted-foreground">{c.groups}</h2>{!groups.length ? <p className="text-sm text-muted-foreground">{c.start}</p> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{groups.map(g=><Link key={g.id} to={localizeHref(locale,libraryHref(g.id))} className="flex min-w-0 items-center gap-3 rounded-xl border p-4 hover:bg-muted/40"><Layers className="size-5 shrink-0 text-muted-foreground" /><div className="min-w-0"><h3 className="break-words font-medium">{g.name}</h3><p className="text-xs text-muted-foreground">{c.folders} {g.folderCount} · {c.unclassified} {g.unclassifiedCount}</p></div></Link>)}</div>}</section>;
}
export function LibraryFolders({ data, groupId, edit }: { data: LibraryView; groupId: string; edit: (e: LibraryEditor)=>void }) {
  const { messages, locale } = useI18n(), c = messages.library;
  return <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-medium">{c.folders}</h2>{data.canOrganize && <Button variant="outline" onClick={()=>edit({ kind: "folder", groupId })}><FolderPlus className="size-4" />{c.newFolder}</Button>}</div>{!data.folders.length && <p className="text-sm text-muted-foreground">{c.emptyFolders}</p>}<div className="grid gap-3 sm:grid-cols-2">{data.folders.map(f=><div key={f.id} className="flex min-w-0 items-center rounded-xl border"><Link className="flex min-w-0 flex-1 items-center gap-3 p-4 hover:bg-muted/40" to={localizeHref(locale,libraryHref(groupId,f.id))}><Folder className="size-5 shrink-0 text-muted-foreground" /><span className="min-w-0 flex-1 break-words font-medium">{f.name}</span><span className="text-sm text-muted-foreground">{f.count}</span></Link>{data.canConfigure && <Button variant="ghost" size="icon" className="mr-2 shrink-0" aria-label={`${c.editFolder} ${f.name}`} onClick={()=>edit({ kind: "folder", groupId, folder: f })}><MoreHorizontal className="size-4" /></Button>}</div>)}</div></section>;
}
function LibraryItemRow({ item, canOrganize, organize }: { item: LibraryItem; canOrganize: boolean; organize: (v: LibraryItem)=>void }) {
  const { messages, locale } = useI18n(), c = messages.library;
  return <div className="flex min-w-0 items-center gap-2 p-3 sm:p-4"><Link className="flex min-w-0 flex-1 items-center gap-3 rounded-lg p-1 hover:bg-muted/40" to={localizeHref(locale,`/tasks/${item.id}`)}><FileText className="size-5 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><h3 className="break-words font-medium">{item.title}</h3>{item.description && <p className="mt-1 line-clamp-2 break-words text-sm text-muted-foreground">{item.description}</p>}<p className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground">{item.placements.filter(p=>p.folderId).map(p=><span key={p.groupId}>{p.groupName} / {p.folderName}</span>)}</p></div></Link><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label={`${c.manage} ${item.title}`} />}><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={!canOrganize} onClick={()=>organize(item)}>{c.organize}</DropdownMenuItem><DropdownMenuItem render={<Link to={localizeHref(locale,`/tasks/${item.id}?view=execution`)} />}>{messages.workPages.execution}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>;
}
export function LibraryItems({ data, location, organize, changePage }: { data: LibraryView; location: LibraryLocation; organize: (v: LibraryItem)=>void; changePage: (offset: number)=>void }) {
  const { messages } = useI18n(), c = messages.library;
  return <section className="space-y-3"><h2 className="text-sm font-medium text-muted-foreground">{location.directory ? c.unclassified : c.matches} · {data.total}</h2>{!data.items.length ? <p className="py-10 text-center text-muted-foreground">{location.query ? c.noMatches : c.empty}</p> : <div className="divide-y rounded-xl border bg-background">{data.items.map(item=><LibraryItemRow key={item.id} item={item} canOrganize={data.canOrganize} organize={organize} />)}</div>}<div className="flex flex-wrap items-center gap-3">{location.offset > 0 && <Button variant="ghost" onClick={()=>changePage(Math.max(0,location.offset - 20))}>{c.previous}</Button>}{data.nextOffset !== null && <Button variant="ghost" onClick={()=>changePage(data.nextOffset!)}>{c.next}</Button>}</div></section>;
}
export function selectedFolder(data: LibraryView | null, folderId?: string): LibraryFolder | undefined { return data?.folders.find(f=>f.id===folderId); }
