// AI plan contracts
export type {
  StructuredSuggestion,
  AiFeatureToolSpec,
  StructuredAiFeature,
  PlanBlueprint,
  PlanBlueprintNode,
  PlanBlueprintTaskNode,
  PlanBlueprintCheckpointNode,
  PlanBlueprintConditionNode,
  PlanBlueprintWaitNode,
  PlanBlueprintEdge,
  CompiledPlanCompletionPolicy,
  PlanCompileIssue,
  AIPlanNode,
  AIPlanNodeType,
  AITaskNode,
  AICheckpointNode,
  AIConditionNode,
  AIWaitNode,
  AIPlanEdge,
  AIPlanCompletionPolicy,
  AIPlanOutput,
  AIPlanValidationResult,
  PreparedAiFeatureSpec,
  TaskPlanStatus,
  TaskPlanNodeType,
  TaskPlanNodeStatus,
  TaskPlanEdgeType,
  TaskPlanNodeExecutionMode,
  TaskPlanNodeBlockingReason,
  TaskPlanNode,
  TaskPlanEdge,
  TaskPlanGraph,
  SavedTaskPlanGraph,
  TaskPlanGraphResponse,
} from "./ai";

// AI feature request/response contracts
export type {
  GenerateTaskPlanRequest,
  TaskWorkspaceChatRequest,
  TaskWorkspaceChatResponse,
  TaskWorkspaceUpdateProposal,
  ConflictAnalysisResult,
  TimeslotSuggestionResult,
} from "./ai";

export {
  ANALYZE_SCHEDULE_CONFLICTS_TOOL_NAME,
  CONFLICTS_SYSTEM_PROMPT,
  DISPATCH_NEXT_TASK_ACTION_TOOL_NAME,
  DISPATCH_TASK_SYSTEM_PROMPT,
  GENERATE_PLAN_SYSTEM_PROMPT,
  SUGGEST_SYSTEM_PROMPT,
  SUGGEST_TASK_COMPLETIONS_TOOL_NAME,
  SUGGEST_TASK_TIMESLOTS_TOOL_NAME,
  TIMESLOTS_SYSTEM_PROMPT,
  analyzeScheduleConflictsToolSpec,
  buildAnalyzeConflictsFeatureSpec,
  buildDispatchTaskFeatureSpec,
  GENERATE_TASK_PLAN_GRAPH_TOOL_DESCRIPTION,
  GENERATE_TASK_PLAN_GRAPH_TOOL_NAME,
  buildGeneratePlanFeatureInputText,
  buildGeneratePlanFeatureSpec,
  buildSuggestFeatureSpec,
  buildSuggestTimeslotsFeatureSpec,
  dispatchNextTaskActionToolSpec,
  generateTaskPlanGraphToolPayloadSchema,
  generateTaskPlanGraphToolSpec,
  PlanCompileError,
  suggestTaskCompletionsToolSpec,
  suggestTaskTimeslotsToolSpec,
  validateAIPlanOutput,
  validatePreparedFeaturePayload,
} from "./ai";
