import type {
  GoalOperationalBrief,
  GoalStatus,
  GoalSuccessCriterion,
  GoalWorkingSetSubjectType,
} from "@chrona/contracts";
import type { GoalProjection } from "@chrona/domain";

export type GoalArtifactData = {
  id: string;
  taskId: string;
  runId: string;
  title: string;
  type: string;
  uri: string;
  contentPreview: string | null;
  createdAt: string;
  operations: {
    canOpen: boolean;
    canCopy: boolean;
    canDownload: boolean;
    downloadHref: string | null;
  };
};

export type GoalAcceptedResultData = {
  runId: string;
  acceptedAt: string | null;
  completedAt: string | null;
  summary: string;
  artifacts: GoalArtifactData[];
};

export type GoalTaskGroup = "attention" | "active" | "planned" | "completed";

export type GoalTaskData = {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  kind: string;
  dueAt: string | null;
  updatedAt: string;
  attention: string | null;
  group: GoalTaskGroup;
  acceptedResult: GoalAcceptedResultData | null;
};

export type GoalAssetData = {
  id: string;
  label: string;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  currentVersion: number | null;
  sourceArtifact: GoalArtifactData;
  currentArtifact: GoalArtifactData;
  provenance: {
    sourceTaskId: string;
    sourceRunId: string | null;
    sourceArtifactId: string;
    currentArtifactId: string;
    unchanged: boolean;
  };
};

export type GoalAchievementConfirmation = {
  note: string;
  actorType: string;
  actorId: string | null;
  confirmedAt: string;
  evidenceArtifactIds: string[];
};

export type GoalActivityData = {
  id: string;
  type: string;
  title: string;
  detail: string | null;
  occurredAt: string;
  taskId: string | null;
};


export type GoalWorkingSetItemData = {
  id: string;
  subjectType: GoalWorkingSetSubjectType;
  subjectId: string;
  label: string;
  snapshot: unknown;
  rank: number;
  createdAt: string;
  updatedAt: string;
};
export type GoalData = {
  id: string;
  workspaceId: string;
  title: string;
  titleSource: "user" | "ai";
  titleRenameNoticeSeenAt: string | null;
  description: string | null;
  successCriteria: GoalSuccessCriterion[];
  status: GoalStatus;
  mode: "workspace" | "archive";
  nextReviewAt: string | null;
  createdAt: string;
  updatedAt: string;
  achievedAt: string | null;
  stoppedAt: string | null;
  projection: GoalProjection;
  primaryAction: {
    kind: GoalProjection["nextAction"];
    taskId: string | null;
  };
  outcome: {
    primaryResult: GoalArtifactData | null;
    confirmation: GoalAchievementConfirmation | null;
    criteria: Array<GoalSuccessCriterion & { evidenceArtifactIds: string[] }>;
  };
  workbench: {
    brief: GoalOperationalBrief | null;
    briefRevisionCount: number;
    pendingInboxCount: number;
    workingSet: GoalWorkingSetItemData[];
    focus: {
      needsYou: GoalTaskData[];
      inProgress: GoalTaskData[];
      newResults: GoalTaskData[];
      upNext: GoalTaskData[];
    };
  };
  taskGroups: Record<GoalTaskGroup, GoalTaskData[]>;
  tasks: GoalTaskData[];
  acceptedResults: Array<GoalAcceptedResultData & { taskId: string; taskTitle: string }>;
  assets: GoalAssetData[];
  activity: GoalActivityData[];
};

export type GoalCopy = {
  title: string;
  subtitle: string;
  emptyTitle: string;
  emptyDescription: string;
  openGoal: string;
  createGoal: string;
  createGoalDescription: string;
  removeCriterion: string;
  addCriterion: string;
  backToGoals: string;
  ongoingWorkspace: string;
  outcomeArchive: string;
  archiveDescription: string;
  workspaceDescription: string;
  pendingInbox: string;
  controlPlane: string;
  workbench: string;
  operationalBrief: string;
  outcomeLabel: string;
  currentFocus: string;
  strategy: string;
  constraints: string;
  editBrief: string;
  saveBrief: string;
  saving: string;
  workingSet: string;
  workingSetDescription: string;
  editWorkingSet: string;
  saveWorkingSet: string;
  noWorkingSet: string;
  focusQueue: string;
  needsYou: string;
  inProgress: string;
  stable: string;
  stableDescription: string;
  newResults: string;
  upNext: string;
  composer: string;
  expectedOutcome: string;
  expectedOutcomePlaceholder: string;
  selectedContext: string;
  actionPreview: string;
  createBoundedTaskPreview: string;
  taskInspector: string;
  returnToGoal: string;
  overview: string;
  tasksSection: string;
  resultsAssets: string;
  history: string;
  outcome: string;
  primaryResult: string;
  noPrimaryResult: string;
  successCriteria: string;
  progress: string;
  boundedTasks: string;
  acceptedResults: string;
  processResult: string;
  processResultDescription: string;
  addToWorkingSet: string;
  retainAsAsset: string;
  linkCriterion: string;
  noCriterion: string;
  processedResult: string;
  confirmCriterion: string;
  confirmCriterionDescription: string;
  criterionEvidenceNote: string;
  applyReview: string;
  applyReviewDescription: string;
  reviewSummary: string;
  reviewTaskSuggestion: string;
  assets: string;
  nextReview: string;
  noReview: string;
  noTasks: string;
  noAssets: string;
  noAcceptedResults: string;
  sourceEvidence: string;
  currentVersion: string;
  provenance: string;
  provenanceUnchanged: string;
  sourceTask: string;
  role: string;
  assetStatus: string;
  pause: string;
  resume: string;
  stop: string;
  achieve: string;
  startReview: string;
  addTask: string;
  reviewTaskTitle: string;
  reviewTaskDescription: string;
  addTaskTitle: string;
  taskTitleLabel: string;
  taskDescriptionLabel: string;
  taskTitlePlaceholder: string;
  taskDescriptionPlaceholder: string;
  createTask: string;
  creatingTask: string;
  confirmAchievement: string;
  confirmAchievementDescription: string;
  confirmationLabel: string;
  confirmationPlaceholder: string;
  evidenceLabel: string;
  evidenceDescription: string;
  evidenceRequired: string;
  confirmedBy: string;
  confirmationNote: string;
  currentUser: string;
  sourceRun: string;
  evidenceCount: string;
  outcomeSummary: string;
  verifiedOutcome: string;
  supportingEvidence: string;
  resultActions: string;
  technicalDetails: string;
  outcomeDocument: string;
  copyDocument: string;
  cancel: string;
  confirming: string;
  actionError: string;
  status: Record<GoalStatus, string>;
  activity: Record<string, string>;
  attention: Record<string, string>;
  nextAction: Record<string, string>;
  taskGroups: Record<GoalTaskGroup, string>;
  taskStatus: Record<string, string>;
  assetRoles: Record<string, string>;
  assetStatuses: Record<string, string>;
  criteriaProgress: string;
  taskProgress: string;
  achievedAt: string;
  acceptedAt: string;
  immutableResult: string;
  openTask: string;
  open: string;
  copy: string;
  copied: string;
  download: string;
  showDetails: string;
  hideDetails: string;
  createFromResult: string;
  createFromResultTitle: string;
  createFromResultDescription: string;
  goalTitleLabel: string;
  goalDescriptionLabel: string;
  goalDescriptionPlaceholder: string;
  criterionLabel: string;
  criterionPlaceholder: string;
  selectedAssets: string;
  selectedAssetsRequired: string;
  proposedFollowUp: string;
  proposedFollowUpDescription: string;
  createAndContinue: string;
  creatingGoal: string;
  promotionError: string;
  assetWorkbench: {
    title: string;
    description: string;
    library: string;
    inbox: string;
    allAssets: string;
    noAssets: string;
    noAssetsDescription: string;
    inboxClear: string;
    inboxClearDescription: string;
    searchAssets: string;
    allTypes: string;
    documents: string;
    forms: string;
    pages: string;
    files: string;
    allSources: string;
    allStatuses: string;
    draft: string;
    processing: string;
    failed: string;
    archived: string;
    recentlyUpdated: string;
    oldestUpdated: string;
    name: string;
    recent: string;
    match: string;
    sourceTask: string;
    changeSummary: string;
    assetDestination: string;
    noConfidentAssetMatch: string;
    candidateFromAcceptedResult: string;
    createNewAsset: string;
    appendToAsset: string;
    createAsset: string;
    appendVersion: string;
    rejectCandidate: string;
    candidateUpdateFailed: string;
    pageSafetyWarning: string;
    genericFileDescription: string;
    formSchema: string;
    fillMode: string;
    designMode: string;
    submitForm: string;
    requiredField: string;
    invalidFormDefinition: string;
    formSubmissionStored: string;
    submissions: string;
    noSubmissions: string;
    downloadSubmission: string;
    documentContent: string;
    draftAutosaved: string;
    draftSaved: string;
    publishVersion: string;
    newFormalVersionCreated: string;
    manualEditSummary: string;
    actionFailed: string;
    titleLabel: string;
    renamed: string;
    save: string;
    asset: string;
    type: string;
    source: string;
    formalVersion: string;
    saveDraft: string;
    downloadSource: string;
    export: string;
    exportReady: string;
    restore: string;
    assetRestored: string;
    assetArchived: string;
    versions: string;
    ai: string;
    formalVersionFallback: string;
    recoveredVersion: string;
    recover: string;
    modificationRequest: string;
    modificationPlaceholder: string;
    expectedModifiedOutcome: string;
    versionBoundTaskCreated: string;
    createAiTask: string;
    provenanceDescription: string;
    closeAssetWorkspace: string;
    documentKind: string;
    formKind: string;
    pageKind: string;
    fileKind: string;
    manualSource: string;
    aiTaskSource: string;
    inboxSource: string;
    restoredSource: string;
    importedSource: string;
  };
};
