import { afterEach, describe, expect, it, vi } from "vitest";
import {
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
  within,
} from "@testing-library/react";
import { createMemoryRouter, RouterProvider } from "react-router-dom";
import { GoalListPage } from "./goal-list-page";
import { GoalWorkspacePage } from "./goal-workspace-page";
import { CreateGoalFromResultDialog } from "./create-goal-from-result-dialog";
import type { GoalArtifactData, GoalCopy, GoalData } from "../model/goal-types";

const { apiJsonMock, promoteTaskToGoalMock, createGoalWithFirstTaskMock, uuidv4Mock } = vi.hoisted(
  () => ({
    apiJsonMock: vi.fn(async () => ({ id: "workspace-default" })),
    promoteTaskToGoalMock: vi.fn(async () => ({ id: "goal-promoted" })),
    createGoalWithFirstTaskMock: vi.fn(async () => ({
      goal: { id: "goal-created" },
      taskId: "task-created",
    })),
    uuidv4Mock: vi.fn(() => "goal-idempotency-key"),
  }),
);
vi.mock("uuid", () => ({ v4: uuidv4Mock }));
vi.mock("@shared/http", () => ({ apiJson: apiJsonMock }));
vi.mock("../browser-api", () => ({
  runGoalAction: vi.fn(async () => ({})),
  createGoalTask: vi.fn(async () => ({ taskId: "task-created", goal: {} })),
  createGoalWithFirstTask: createGoalWithFirstTaskMock,
  promoteTaskToGoal: promoteTaskToGoalMock,
  updateGoalBrief: vi.fn(async () => ({})),
}));
vi.mock("@chrona/i18n/react", () => ({ useLocale: () => "en" }));

const copy: GoalCopy = {
  title: "Goals",
  subtitle: "Durable outcomes",
  emptyTitle: "No goals",
  emptyDescription: "Create one",
  createGoal: "Create Goal",
  createGoalDescription: "Define a durable outcome",
  goalPortfolio: "Long-horizon outcomes",
  defineOutcome: "Define the long-term outcome",
  defineOutcomeDescription: "Set the durable result this Goal should reach.",
  goalOutcomePlaceholder: "Describe the durable outcome",
  goalDescriptionHelp: "Keep scope durable and observable.",
  startFirstTask: "Start with one bounded task",
  startFirstTaskDescription: "Create the first concrete step.",
  firstTaskLabel: "First bounded task",
  firstTaskPlaceholder: "Describe the first task",
  attentionGoalsDescription: "Goals that need a decision or intervention.",
  progressGoalsDescription: "Goals with work currently moving.",
  quietGoals: "No immediate action",
  archiveCardSummary:
    "Verified outcome, confirmation, and supporting evidence retained.",
  viewOutcome: "View outcome",
  removeCriterion: "Remove criterion",
  addCriterion: "Add criterion",
  openGoal: "Open Goal",
  backToGoals: "All Goals",
  ongoingWorkspace: "Ongoing Workspace",
  outcomeArchive: "Outcome Archive",
  archiveDescription: "Retained outcome record",
  pendingInbox: "Review {count} inbox item(s)",
  workspaceDescription: "Bounded ongoing work",
  controlPlane: "Goal Control Plane",
  workbench: "Workbench",
  operationalBrief: "Operational brief",
  outcomeLabel: "Intended outcome",
  currentFocus: "Current focus",
  strategy: "Current strategy",
  constraints: "Constraints",
  editBrief: "Edit brief",
  saveBrief: "Save brief",
  saving: "Saving",
  briefDescription: "The durable definition behind the current queue.",
  currentFocusDescription: "One clear queue for current Goal work.",
  focusClear: "Focus queue clear",
  focusClearDescription: "No work currently needs attention.",
  completedShort: "completed",
  confirmedShort: "confirmed",
  scheduledShort: "scheduled",
  stable: "Stable and paused",
  stableDescription: "Goals without immediate attention",
  focusQueue: "Focus queue",
  needsYou: "Needs you",
  inProgress: "In progress",
  newResults: "New results",
  upNext: "Up next",
  composer: "Compose bounded work",
  expectedOutcome: "Expected outcome",
  expectedOutcomePlaceholder: "Observable result",
  generateReview: "Generate AI review",
  generatingReview: "Generating review proposal…",
  rejectProposal: "Reject proposal",
  proposalFailed: "Review generation failed",
  proposalPending: "Pending decision",
  proposalStale: "This item is stale",
  proposalSource: "Generated by a bounded read-only Task",
  proposalNoItems: "No review items are available",
  actionPreview: "Action preview",
  createBoundedTaskPreview: "Create one bounded task with an automatic snapshot of accepted Goal results.",
  taskInspector: "Task inspector",
  returnToGoal: "Return to Goal",
  overview: "Overview",
  tasksSection: "Work",
  resultsAssets: "Results & Assets",
  history: "History",
  processResult: "Use in Goal",
  processResultDescription: "Retain accepted deliverables",
  addToWorkingSet: "Add to working set",
  retainAsAsset: "Retain as asset",
  linkCriterion: "Link criterion",
  noCriterion: "No criterion",
  processedResult: "Processed",
  confirmCriterion: "Confirm criterion",
  confirmCriterionDescription: "Confirm with evidence",
  criterionEvidenceNote: "Evidence note",
  applyReview: "Apply review",
  applyReviewDescription: "Review changes",
  reviewSummary: "Review conclusion",
  reviewTaskSuggestion: "Suggested task",
  outcome: "Outcome",
  primaryResult: "Final outcome",
  confirmedOutcome: "User-confirmed outcome",
  retainedDeliverable: "Outcome document",
  noPrimaryResult: "No final result",
  successCriteria: "Success criteria",
  progress: "Progress",
  boundedTasks: "Bounded tasks",
  acceptedResults: "Accepted results",
  assets: "Goal assets",
  nextReview: "Next review",
  noReview: "No review",
  noTasks: "No tasks",
  noAssets: "No assets",
  noAcceptedResults: "No accepted results",
  sourceEvidence: "Source evidence",
  currentVersion: "Current version",
  provenance: "Provenance",
  provenanceUnchanged: "Original accepted artifact",
  sourceTask: "Source task",
  role: "Role",
  assetStatus: "Asset status",
  pause: "Pause Goal",
  resume: "Resume Goal",
  stop: "Stop pursuing",
  achieve: "Confirm achieved",
  startReview: "Start Goal review",
  addTask: "Add task",
  reviewTaskTitle: "Review Goal progress",
  reviewTaskDescription: "Review evidence and next actions",
  addTaskTitle: "Add bounded task",
  taskTitleLabel: "Task title",
  taskDescriptionLabel: "Task instructions",
  taskTitlePlaceholder: "Bounded work",
  taskDescriptionPlaceholder: "Context and outcome",
  createTask: "Create task",
  creatingTask: "Creating task",
  confirmAchievement: "Confirm achieved?",
  confirmAchievementDescription: "Task completion is not enough",
  confirmationLabel: "Confirmation",
  confirmationPlaceholder: "Evidence",
  evidenceLabel: "Evidence used for confirmation",
  evidenceDescription: "Select retained evidence",
  evidenceRequired: "Select evidence",
  confirmedBy: "Confirmed by",
  confirmationNote: "Achievement confirmation",
  cancel: "Cancel",
  confirming: "Confirming…",
  actionError: "Action failed",
  currentUser: "Current user",
  sourceRun: "Source run",
  evidenceCount: "{count} linked evidence item(s)",
  outcomeSummary: "Outcome summary",
  verifiedOutcome: "Verified outcome",
  supportingEvidence: "Supporting evidence",
  resultActions: "Result actions",
  technicalDetails: "Technical details",
  outcomeDocument: "Outcome document",
  copyDocument: "Copy document",
  status: {
    Draft: "Draft",
    Active: "Active",
    Paused: "Paused",
    Achieved: "Achieved",
    Stopped: "Stopped",
  },
  activity: {
    idle: "Idle",
    work_active: "Work active",
    review_due: "Review due",
  },
  attention: {
    none: "No attention",
    needs_input: "Needs input",
    blocked: "Blocked",
    failed: "Failed",
  },
  nextAction: {
    none: "No action",
    review_criteria: "Review criteria",
    review: "Review",
    resolve_attention: "Resolve",
    continue_work: "Continue work",
    resume: "Resume",
    confirm_outcome: "Confirm outcome",
  },
  taskGroups: {
    attention: "Needs attention",
    active: "Active",
    planned: "Planned",
    completed: "Completed",
  },
  taskStatus: { Completed: "Completed", Ready: "Ready" },
  assetRoles: { Evidence: "Evidence", PrimaryOutcome: "Primary outcome" },
  assetStatuses: { Approved: "Approved" },
  criteriaProgress: "{completed} of {total} confirmed",
  taskProgress: "{completed} of {total} tasks completed",
  achievedAt: "Achieved",
  acceptedAt: "Accepted",
  immutableResult: "Immutable accepted result",
  openTask: "Open task",
  open: "Open",
  copy: "Copy",
  copied: "Copied",
  download: "Download",
  showDetails: "Details",
  hideDetails: "Collapse",
  createFromResult: "Create Goal and continue",
  createFromResultTitle: "Continue as Goal",
  createFromResultDescription: "Preview promotion",
  goalTitleLabel: "Goal title",
  goalDescriptionLabel: "Description",
  goalDescriptionPlaceholder: "Describe outcome",
  criterionLabel: "Success criterion",
  criterionPlaceholder: "Confirm outcome",
  selectedAssets: "Selected assets",
  selectedAssetsRequired: "Select an asset",
  proposedFollowUp: "Proposed follow-up",
  proposedFollowUpDescription: "Create bounded work",
  createAndContinue: "Create Goal and continue",
  creatingGoal: "Creating",
  promotionError: "Promotion failed",
  suggestedCriterion: "System suggested",
  suggestedGoalName: "Suggested Goal name",
  suggestedGoalNameDescription: "Copied from the promoted Task",
  renameSuggestedGoal: "Rename suggested Goal",
  renameGoal: "Rename",
  assetWorkbench: {
    title: "Assets and result Inbox",
    description: "Durable Goal assets",
    library: "Library",
    inbox: "Inbox",
    allAssets: "All assets",
    noAssets: "No matching Goal assets",
    noAssetsDescription: "Review Inbox candidates",
    inboxClear: "Inbox clear",
    inboxClearDescription: "Accepted Results appear here",
    searchAssets: "Search assets",
    allTypes: "All types",
    documents: "Documents",
    forms: "Forms",
    pages: "Pages",
    files: "Files",
    structuredResults: "Structured results",
    structuredResultDescription: "Validated read-only result",
    invalidStructuredResult: "Invalid structured result",
    structuredResultContent: "Structured result content",
    allSources: "All sources",
    allStatuses: "All statuses",
    draft: "Draft",
    processing: "Processing",
    failed: "Failed",
    archived: "Archived",
    archivedEmpty: "No archived assets",
    archivedEmptyDescription: "Archived assets appear here.",
    recentlyUpdated: "Recently updated",
    oldestUpdated: "Oldest updated",
    name: "Name",
    recent: "Recent",
    assetCount: "assets",
    filters: "Filters",
    activeFilters: "Active filters",
    clearFilters: "Clear",
    ruleBasedMatch: "Rule-based name match",
    sourceTask: "Source Task",
    changeSummary: "Change summary",
    assetDestination: "Asset destination",
    createNewAsset: "Create a new asset",
    appendToAsset: "Append to {asset}",
    noRuleBasedMatch: "No rule-based name match",
    ruleBasedMatchDescription: "Names overlap for the same asset type",
    noRuleBasedMatchDescription: "No same-type asset name overlaps",
    candidateFromAcceptedResult:
      "Candidate derived from accepted result “{result}”",
    createAsset: "Create asset",
    appendVersion: "Append version",
    rejectCandidate: "Reject",
    candidateUpdateFailed: "Candidate update failed",
    pageSafetyWarning: "Generated Page runs in an isolated frame.",
    genericFileDescription:
      "Generic files preserve immutable source provenance.",
    formSchema: "Form definition JSON",
    fillMode: "Fill",
    designMode: "Design",
    submitForm: "Submit response",
    requiredField: "Required",
    invalidFormDefinition: "Invalid Form definition",
    formSubmissionStored: "Form submission stored",
    submissions: "Submissions",
    noSubmissions: "No submissions",
    downloadSubmission: "Download submission",
    documentContent: "Document content",
    draftAutosaved: "Draft autosaved",
    draftSaved: "Draft saved",
    publishVersion: "Publish version",
    newFormalVersionCreated: "New formal version created",
    manualEditSummary: "Manual Workbench edit",
    actionFailed: "Action failed",
    titleLabel: "Title",
    renamed: "Renamed",
    save: "Save",
    asset: "Asset",
    type: "Type",
    source: "Source",
    formalVersion: "Formal version",
    saveDraft: "Save draft",
    downloadSource: "Download source",
    export: "Export",
    exportReady: "Export ready",
    exportMarkdown: "Markdown",
    exportPdf: "PDF",
    exportJson: "JSON",
    restore: "Restore",
    assetRestored: "Asset restored",
    assetArchived: "Asset archived",
    versions: "Versions",
    ai: "AI",
    formalVersionFallback: "Formal version",
    recoveredVersion: "Recovered v{version} as a new version",
    recover: "Recover",
    modificationRequest: "Modification request",
    modificationPlaceholder: "Describe a bounded change",
    expectedModifiedOutcome: "A reviewed new version of {asset}",
    versionBoundTaskCreated: "Version-bound Task created",
    assetsNavigation: "Goal assets",
    assetDetails: "Details",
    collapseAssets: "Collapse assets",
    collapseDetails: "Collapse details",
    openAssets: "Browse assets",
    openDetails: "Versions and details",
    currentVersion: "Current version",
    draftAvailable: "Draft available",
    noDraft: "No draft",
    originalFilename: "Original filename",
    mimeType: "MIME type",
    updated: "Updated",
    archiveAsset: "Archive asset",
    restoreAsset: "Restore asset",
    aiModificationDescription:
      "Creates a bounded Task based on this exact version.",
    createAiTask: "Create AI Task",
    provenanceDescription: "{kind} · provenance",
    closeAssetWorkspace: "Close asset workspace",
    documentKind: "Document",
    formKind: "Form",
    pageKind: "Page",
    fileKind: "File",
    manualSource: "Manual",
    aiTaskSource: "AI Task",
    inboxSource: "Inbox",
    restoredSource: "Restored",
    importedSource: "Imported",
    aiRecommendation: "AI recommendation",
    generateAiRecommendation: "Generate AI recommendation",
    generatingAiRecommendation: "Generating recommendation…",
    aiRecommendationFailed: "AI recommendation failed",
    applyAiRecommendation: "Apply AI recommendation",
    aiDecisionCreate: "Create a new asset",
    aiDecisionAppend: "Append to {asset}",
    aiDecisionSeparate: "Keep as a separate asset",
    rationale: "Rationale",
    differenceSummaryLabel: "Difference summary",
    certainty: "Certainty: {certainty}",
    certaintyLow: "low",
    certaintyMedium: "medium",
    certaintyHigh: "high",
    evidence: "Evidence",
    counterEvidence: "Counter-evidence",
    aiSource: "Generated by {provider}{model}",
    proposalStale: "This recommendation is stale.",
    proposalApplied: "AI recommendation applied",
  },
};

const artifact: GoalArtifactData = {
  id: "artifact-1",
  taskId: "task-1",
  runId: "run-1",
  title: "Final result",
  type: "summary",
  uri: "chrona://result",
  contentPreview: "Final immutable outcome",
  createdAt: "2026-07-01T00:00:00.000Z",
  operations: {
    canOpen: true,
    canCopy: true,
    canDownload: false,
    downloadHref: null,
  },
};

const baseGoal: GoalData = {
  id: "goal-1",
  workspaceId: "ws-1",
  title: "Reach durable outcome",
  titleSource: "user",
  titleRenameNoticeSeenAt: null,
  description: "Across bounded tasks",
  status: "Active",
  mode: "workspace",
  nextReviewAt: null,
  createdAt: "2026-07-01T00:00:00.000Z",
  updatedAt: "2026-07-01T00:00:00.000Z",
  achievedAt: null,
  stoppedAt: null,
  successCriteria: [
    {
      id: "criterion",
      kind: "user_confirmed",
      description: "User confirms outcome",
      satisfied: false,
      confirmedAt: null,
      proposalStatus: "confirmed",
    },
  ],
  projection: {
    lifecycle: "Active",
    activity: "idle",
    attention: "none",
    nextAction: "confirm_outcome",
    completedTaskCount: 0,
    totalTaskCount: 0,
    criteriaSatisfiedCount: 0,
    criteriaTotalCount: 1,
  },
  primaryAction: { kind: "confirm_outcome", taskId: null },
  outcome: {
    primaryResult: null,
    confirmation: null,
    criteria: [
      {
        id: "criterion",
        kind: "user_confirmed",
        description: "User confirms outcome",
        satisfied: false,
        confirmedAt: null,
        proposalStatus: "confirmed",
        evidenceArtifactIds: [],
      },
    ],
  },
  taskGroups: { attention: [], active: [], planned: [], completed: [] },
  tasks: [],
  acceptedResults: [],
  workbench: {
    pendingInboxCount: 0,
    brief: {
      outcome: "Reach durable outcome",
      currentFocus: "Confirm next bounded step",
      strategy: "Use accepted evidence",
      constraints: ["Retain provenance"],
    },
    briefRevisionCount: 1,
    focus: { needsYou: [], inProgress: [], newResults: [], upNext: [] },
  },
  reviewProposals: [],
  assets: [
    {
      id: "asset-1",
      label: "Outcome evidence",
      role: "Evidence",
      status: "Approved",
      createdAt: artifact.createdAt,
      updatedAt: artifact.createdAt,
      currentVersion: 1,
      sourceArtifact: artifact,
      currentArtifact: artifact,
      provenance: {
        sourceTaskId: "task-1",
        sourceRunId: "run-1",
        sourceArtifactId: artifact.id,
        currentArtifactId: artifact.id,
        unchanged: true,
      },
    },
  ],
  activity: [],
};

function renderInRouter(node: React.ReactNode, initialEntry = "/en/goals") {
  const router = createMemoryRouter([{ path: "*", element: node }], {
    initialEntries: [initialEntry],
  });
  return { ...render(<RouterProvider router={router} />), router };
}

describe("Goal pages", () => {
  afterEach(() => cleanup());
  it("shows the empty list state", () => {
    renderInRouter(<GoalListPage goals={[]} copy={copy} />);
    expect(screen.getByText("No goals")).toBeInTheDocument();
  });

  it("creates a Goal with a library-generated idempotency key", async () => {
    renderInRouter(<GoalListPage goals={[]} copy={copy} />);
    fireEvent.click(screen.getByRole("button", { name: "Create Goal" }));
    const dialog = screen.getByRole("dialog");
    fireEvent.change(within(dialog).getByLabelText("Intended outcome"), {
      target: { value: "Plan a two-week trip to Japan" },
    });
    fireEvent.change(within(dialog).getByLabelText("First bounded task"), {
      target: { value: "Draft the itinerary and budget" },
    });
    fireEvent.click(within(dialog).getByRole("button", { name: "Create Goal" }));

    await waitFor(() =>
      expect(createGoalWithFirstTaskMock).toHaveBeenCalledWith({
        workspaceId: "workspace-default",
        intendedOutcome: "Plan a two-week trip to Japan",
        firstWorkItem: "Draft the itinerary and budget",
        description: null,
        priority: "High",
        idempotencyKey: "goal-idempotency-key",
      }),
    );
    expect(uuidv4Mock).toHaveBeenCalledOnce();
  });

  it("shows lifecycle, attention, and one primary next action", () => {
    const goal: GoalData = {
      ...baseGoal,
      projection: {
        ...baseGoal.projection,
        activity: "review_due",
        attention: "needs_input",
        nextAction: "resolve_attention",
      },
    };
    renderInRouter(<GoalListPage goals={[goal]} copy={copy} />);
    expect(screen.getByText("Active")).toBeInTheDocument();
    expect(screen.getByText("Needs input")).toBeInTheDocument();
    expect(screen.getByText("Resolve")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /Open Goal/ })).toHaveAttribute(
      "href",
      "/en/goals/goal-1",
    );
  });

  it("puts the final outcome before archive details and exposes provenance", () => {
    const acceptedResult = {
      runId: "run-1",
      acceptedAt: artifact.createdAt,
      completedAt: artifact.createdAt,
      summary: "Accepted result summary",
      artifacts: [artifact],
    };
    const completedTask = {
      id: "task-1",
      title: "Bounded step",
      description: null,
      status: "Completed",
      priority: "High",
      kind: "single",
      dueAt: null,
      updatedAt: artifact.createdAt,
      attention: null,
      group: "completed" as const,
      acceptedResult,
    };
    const goal: GoalData = {
      ...baseGoal,
      status: "Achieved",
      mode: "archive",
      achievedAt: artifact.createdAt,
      projection: {
        ...baseGoal.projection,
        lifecycle: "Achieved",
        nextAction: "none",
        completedTaskCount: 1,
        totalTaskCount: 1,
        criteriaSatisfiedCount: 1,
      },
      primaryAction: { kind: "none", taskId: null },
      outcome: {
        primaryResult: artifact,
        confirmation: {
          note: "Offer accepted",
          actorType: "user",
          actorId: "acceptance-user",
          confirmedAt: artifact.createdAt,
          evidenceArtifactIds: [artifact.id],
        },
        criteria: [
          {
            ...baseGoal.outcome.criteria[0],
            satisfied: true,
            confirmedAt: artifact.createdAt,
            evidenceArtifactIds: [artifact.id],
          },
        ],
      },
      tasks: [completedTask],
      taskGroups: {
        attention: [],
        active: [],
        planned: [],
        completed: [completedTask],
      },
      acceptedResults: [
        {
          ...acceptedResult,
          taskId: completedTask.id,
          taskTitle: completedTask.title,
        },
      ],
    };
    const router = createMemoryRouter(
      [{ path: "*", element: <GoalWorkspacePage goal={goal} copy={copy} /> }],
      { initialEntries: ["/en/goals/goal-1"] },
    );
    render(<RouterProvider router={router} />);
    expect(screen.getByText("Final immutable outcome")).toBeInTheDocument();
    expect(screen.getByText("Offer accepted")).toBeInTheDocument();
    expect(
      screen.getByRole("heading", { name: "Achievement confirmation" }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("heading", { name: "Outcome document" }),
    ).toBeInTheDocument();
    expect(screen.getByText("Outcome evidence")).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: "Copy document" }),
    ).toBeInTheDocument();
    expect(
      screen.getByText("Technical details").closest("details"),
    ).not.toHaveAttribute("open");
    expect(screen.getByRole("tab", { name: "Overview" })).toHaveAttribute(
      "data-state",
      "active",
    );
    expect(screen.getByText("Bounded step")).toBeInTheDocument();
  });

  it("opens deep-linked sections in a fixed workspace navigation", () => {
    renderInRouter(
      <GoalWorkspacePage goal={baseGoal} copy={copy} />,
      "/en/goals/goal-1?section=history",
    );

    expect(
      screen.getByRole("navigation", { name: "Goal Control Plane" }),
    ).toBeInTheDocument();
    expect(screen.getByRole("tab", { name: "History" })).toHaveAttribute(
      "data-state",
      "active",
    );
    expect(
      screen.getByRole("heading", { name: copy.workspaceDescription }),
    ).toBeInTheDocument();
    expect(document.querySelector("[data-goal-section-scroll]")).toHaveClass(
      "overflow-y-auto",
    );
    expect(document.querySelector('[data-slot="page-frame"]')).toHaveClass(
      "overflow-y-hidden",
    );
  });

  it("shows the active Goal control plane and automatic-context composer", () => {
    const goal: GoalData = {
      ...baseGoal,
      primaryAction: { kind: "none", taskId: null },
      taskGroups: {
        ...baseGoal.taskGroups,
        attention: [
          {
            id: "attention-1",
            title: "Approve research statement",
            description: "Review before submission",
            status: "WaitingForApproval",
            priority: "Urgent",
            kind: "single",
            dueAt: null,
            updatedAt: artifact.createdAt,
            attention: "approval_required",
            group: "attention",
            acceptedResult: null,
          },
        ],
      },
      tasks: [],
    };
    renderInRouter(<GoalWorkspacePage goal={goal} copy={copy} />);
    expect(
      screen.getByText("Current focus", { selector: "h2" }),
    ).toBeInTheDocument();
    expect(screen.getByText("Confirm next bounded step")).toBeInTheDocument();
    expect(screen.queryByText("Approved application package")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Add task" }));
    expect(screen.getByText("Action preview")).toBeInTheDocument();
    expect(screen.queryByText("Selected context")).not.toBeInTheDocument();
  });

  it("labels promotion-derived Goal content as system suggestions", () => {
    const goal: GoalData = {
      ...baseGoal,
      titleSource: "system",
      successCriteria: [
        {
          ...baseGoal.successCriteria[0]!,
          proposalStatus: "proposed",
        },
      ],
      outcome: {
        ...baseGoal.outcome,
        criteria: [
          {
            ...baseGoal.outcome.criteria[0]!,
            proposalStatus: "proposed",
          },
        ],
      },
    };

    renderInRouter(
      <GoalWorkspacePage goal={goal} copy={copy} />,
      "/en/goals/goal-1?section=criteria",
    );

    expect(screen.getByText(copy.suggestedCriterion)).toBeInTheDocument();
    expect(screen.getByText(copy.suggestedGoalName)).toBeInTheDocument();
    expect(
      screen.getByRole("textbox", { name: copy.renameSuggestedGoal }),
    ).toHaveValue(goal.title);
    expect(screen.queryByText(/AI proposed/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/AI-generated Goal/i)).not.toBeInTheDocument();
  });


  it("requires confirmation and retained evidence before achievement", () => {
    const goal: GoalData = {
      ...baseGoal,
      outcome: {
        ...baseGoal.outcome,
        criteria: baseGoal.outcome.criteria.map((criterion) => ({
          ...criterion,
          satisfied: true,
          evidenceArtifactIds: [artifact.id],
        })),
      },
    };
    renderInRouter(<GoalWorkspacePage goal={goal} copy={copy} />);
    fireEvent.click(
      screen.getAllByRole("button", { name: "Confirm achieved" })[0],
    );
    const confirmation = screen.getByRole("textbox", { name: "Confirmation" });
    const submit = screen
      .getAllByRole("button", { name: "Confirm achieved" })
      .at(-1)!;
    fireEvent.change(confirmation, {
      target: { value: "Outcome evidence confirmed" },
    });
    expect(submit).toBeDisabled();
    fireEvent.click(screen.getByRole("checkbox", { name: /Final result/ }));
    expect(submit).toBeEnabled();
  });

  it("shows paused state with a reversible primary action", () => {
    const goal: GoalData = {
      ...baseGoal,
      status: "Paused",
      projection: {
        ...baseGoal.projection,
        lifecycle: "Paused",
        nextAction: "resume",
      },
      primaryAction: { kind: "resume", taskId: null },
    };
    renderInRouter(<GoalWorkspacePage goal={goal} copy={copy} />);
    expect(screen.getByText("Paused")).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: "Resume Goal" }),
    ).toBeInTheDocument();
  });


  it("renders an itemized AI review proposal with explicit per-item decisions", () => {
    const goal: GoalData = {
      ...baseGoal,
      primaryAction: { kind: "review", taskId: null },
      projection: { ...baseGoal.projection, nextAction: "review" },
      reviewProposals: [{
        id: "proposal-1",
        status: "Ready",
        sourceTaskId: "review-task-1",
        sourceRunId: "review-run-1",
        sourceTask: {
          id: "review-task-1",
          title: "Review Goal: Reach durable outcome",
          status: "Completed",
          latestRunId: "review-run-1",
          latestRun: { id: "review-run-1", status: "Completed", errorSummary: null },
        },
        inputSnapshotHash: "sha256:snapshot",
        schemaVersion: 1,
        providerName: "debug",
        modelName: null,
        summary: "One focused change is ready for review.",
        generationError: null,
        appliedAt: null,
        rejectedAt: null,
        createdAt: "2026-07-22T00:00:00.000Z",
        updatedAt: "2026-07-22T00:00:00.000Z",
        items: [{
          id: "proposal-item-1",
          itemId: "current-focus",
          kind: "brief_field",
          payload: { field: "currentFocus", value: "Verify the next outcome" },
          rationale: "Accepted evidence supports a narrower next step.",
          evidenceRefs: [],
          warnings: [],
          dependencyHash: "sha256:dependency",
          decision: "Pending",
          decisionReason: null,
          appliedObjectType: null,
          appliedObjectId: null,
          decidedAt: null,
        }],
      }],
    };
    renderInRouter(<GoalWorkspacePage goal={goal} copy={copy} />);
    fireEvent.click(screen.getByRole("button", { name: "Start Goal review" }));
    expect(screen.getByText("One focused change is ready for review.")).toBeInTheDocument();
    expect(screen.getByText("Accepted evidence supports a narrower next step.")).toBeInTheDocument();
    expect(screen.getByRole("checkbox", { name: "Operational brief: currentFocus" })).toBeChecked();
    expect(screen.getByRole("button", { name: "Reject proposal" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Apply review" })).toBeInTheDocument();
  });
  it("previews selected accepted assets and opens the promoted Goal", async () => {
    const { router } = renderInRouter(
      <CreateGoalFromResultDialog
        taskId="task-1"
        workspaceId="ws-1"
        acceptedRunId="run-1"
        taskTitle="Accepted task"
        taskDescription="Accepted result description"
        artifacts={[
          { id: "artifact-1", title: "Final result", type: "markdown" },
        ]}
        copy={copy}
      />,
    );
    fireEvent.click(
      screen.getByRole("button", { name: "Create Goal and continue" }),
    );
    const dialog = screen.getByRole("dialog");
    expect(within(dialog).getByText("Final result")).toBeInTheDocument();
    fireEvent.click(
      within(dialog).getByRole("button", { name: "Create Goal and continue" }),
    );
    await waitFor(() =>
      expect(promoteTaskToGoalMock).toHaveBeenCalledWith(
        "task-1",
        expect.objectContaining({
          workspaceId: "ws-1",
          acceptedRunId: "run-1",
          artifactIds: ["artifact-1"],
          title: "Accepted task",
        }),
      ),
    );
    await waitFor(() =>
      expect(router.state.location.pathname).toBe("/en/goals/goal-promoted"),
    );
  });
});
