"use client";
import type { Dispatch, RefObject, SetStateAction } from "react";
import { ArrowLeft, CheckCircle2, CircleOff, Plus, Target } from "lucide-react";
import { Badge, Button, Card, CardContent, Input, PageFrame, PageHeader, Tabs, TabsContent } from "@shared/ui";
import type { GoalCopy, GoalData } from "../model/goal-types";
import { LocalizedLink } from "./localized-link";
import { format } from "./goal-workspace-shared";
import { PrimaryOutcome } from "./goal-workspace-primary-outcome";
import { StoppedOutcomeArchive } from "./goal-workspace-stopped-outcome";
import { ActiveSummary, FocusQueue, OperationalBriefCard } from "./goal-workspace-overview";
import { CriteriaCard, CreateTaskDialog, TaskGroupSection } from "./goal-workspace-tasks";
import { GoalHistory } from "./goal-workspace-history";
import { AchievementDialog, ReviewApplyDialog } from "./goal-workspace-review";
import { GoalSectionNavigation, PrimaryAction } from "./goal-workspace-actions";
export type GoalWorkspaceSection="overview"|"work"|"workbench"|"criteria"|"history";
type Props={goal:GoalData;copy:GoalCopy;assetWorkbench?:React.ReactNode;taskDialog:"task"|null;setTaskDialog:Dispatch<SetStateAction<"task"|null>>;renameTitle:string;setRenameTitle:Dispatch<SetStateAction<string>>;renamePending:boolean;renameGoal:()=>Promise<void>;reviewOpen:boolean;setReviewOpen:Dispatch<SetStateAction<boolean>>;achievementOpen:boolean;setAchievementOpen:Dispatch<SetStateAction<boolean>>;section:GoalWorkspaceSection;searchParams:URLSearchParams;setSearchParams:(params:URLSearchParams,options?:{replace?:boolean})=>void;contentScrollRef:RefObject<HTMLDivElement|null>};
export function GoalWorkspaceLayout(props:Props){const{goal,copy,section}=props;const archive=goal.mode==="archive";return <PageFrame mode="workspace" data-domain={section==="workbench"?"workbench":"goals"} className="overflow-y-hidden p-1 sm:p-2"><div className="flex h-full min-h-0 min-w-0 flex-1 flex-col gap-5 overflow-hidden" data-ui-surface-kind="product-authored"><WorkspaceHeader {...props}/><RenameSuggestion {...props}/><Tabs value={section} onValueChange={(value)=>setSection(props,value)} className="min-h-0 min-w-0 flex-1 gap-0"><GoalSectionNavigation section={section} copy={copy}/><div ref={props.contentScrollRef} data-goal-section-scroll className="min-h-0 flex-1 overflow-y-auto overscroll-contain pb-8 [scrollbar-gutter:stable]"><Overview goal={goal} copy={copy} archive={archive}/><Work goal={goal} copy={copy} archive={archive} onAdd={()=>props.setTaskDialog("task")}/><TabsContent value="workbench" className="mt-5">{props.assetWorkbench??<Empty text={copy.noAssets}/>}</TabsContent><TabsContent value="criteria" className="mt-5"><CriteriaCard goal={goal} copy={copy}/></TabsContent><TabsContent value="history" className="mt-5"><GoalHistory goal={goal} copy={copy} isArchive={archive}/></TabsContent></div></Tabs><WorkspaceDialogs {...props}/></div></PageFrame>}
function WorkspaceHeader({goal,copy,setReviewOpen,setTaskDialog,setAchievementOpen}:Props){const description=goal.description?.trim()&&goal.description.trim()!==goal.title.trim()?goal.description:undefined;return <PageHeader surface="workspace" eyebrow={<Button asChild variant="ghost" size="sm" className="w-fit -ml-2"><LocalizedLink href="/goals"><ArrowLeft className="size-4"/>{copy.backToGoals}</LocalizedLink></Button>} title={goal.title} description={description} meta={<GoalMeta goal={goal} copy={copy}/>} actions={<PrimaryAction goal={goal} copy={copy} onStartReview={()=>setReviewOpen(true)} onAddTask={()=>setTaskDialog("task")} onAchieve={()=>setAchievementOpen(true)}/>}/>}
function GoalMeta({goal,copy}:{goal:GoalData;copy:GoalCopy}){const status=goal.status;const Icon=status==="Achieved"?CheckCircle2:status==="Stopped"?CircleOff:Target;const tone=status==="Achieved"?"text-success":status==="Stopped"?"text-muted-foreground":"text-info";return <><span className={`inline-flex items-center gap-1.5 text-sm font-medium ${tone}`}><Icon className="size-4"/>{copy.status[status]}</span>{goal.projection.attention!=="none"?<Badge variant="destructive">{copy.attention[goal.projection.attention]}</Badge>:null}{goal.workbench.pendingInboxCount>0?<Button asChild size="sm" variant="outline"><LocalizedLink href={`/goals/${goal.id}?section=workbench&assetView=inbox`}>{copy.pendingInbox.replace("{count}",String(goal.workbench.pendingInboxCount))}</LocalizedLink></Button>:null}</>}
function RenameSuggestion({goal,copy,renameTitle,setRenameTitle,renamePending,renameGoal}:Props){return (goal.titleSource==="system"||goal.titleSource==="ai")&&!goal.titleRenameNoticeSeenAt?<Card className="border-primary/30 bg-primary/5"><CardContent className="flex flex-col gap-3 pt-6 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-medium">{copy.suggestedGoalName}</p><p className="text-sm text-muted-foreground">{copy.suggestedGoalNameDescription}</p></div><Input aria-label={copy.renameSuggestedGoal} value={renameTitle} onChange={(event)=>setRenameTitle(event.target.value)} className="sm:max-w-sm"/><Button disabled={!renameTitle.trim()||renamePending} onClick={()=>void renameGoal()}>{copy.renameGoal}</Button></CardContent></Card>:null}
function Overview({goal,copy,archive}:{goal:GoalData;copy:GoalCopy;archive:boolean}){return <TabsContent value="overview" className="mt-5">{goal.status==="Stopped"?<StoppedOutcomeArchive goal={goal} copy={copy}/>:archive?<PrimaryOutcome goal={goal} copy={copy}/>:<div className="space-y-8"><section aria-labelledby="goal-control-plane" className="space-y-4"><div><p className="text-xs font-semibold text-info">{copy.ongoingWorkspace}</p><h2 id="goal-control-plane" className="mt-1 text-2xl font-semibold tracking-tight">{copy.currentFocus}</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{copy.currentFocusDescription}</p></div><div className="grid gap-7 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.65fr)]"><FocusQueue goal={goal} copy={copy}/><OperationalBriefCard goal={goal} copy={copy}/></div></section><ActiveSummary goal={goal} copy={copy}/></div>}</TabsContent>}
function Work({goal,copy,archive,onAdd}:{goal:GoalData;copy:GoalCopy;archive:boolean;onAdd:()=>void}){return <TabsContent value="work" className="mt-5"><section className="space-y-6"><div className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-muted-foreground">{copy.boundedTasks}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{format(copy.taskProgress,{completed:goal.projection.completedTaskCount,total:goal.projection.totalTaskCount})}</h2></div>{goal.status==="Active"?<Button size="sm" onClick={onAdd}><Plus className="size-4"/>{copy.addTask}</Button>:null}</div><div className="space-y-7">{goal.tasks.length===0?<Empty text={copy.noTasks}/>:null}<TaskGroupSection group="attention" tasks={goal.taskGroups.attention} copy={copy} defaultOpen goalId={goal.id}/><TaskGroupSection group="active" tasks={goal.taskGroups.active} copy={copy} defaultOpen goalId={goal.id}/><TaskGroupSection group="planned" tasks={goal.taskGroups.planned} copy={copy} defaultOpen goalId={goal.id}/><TaskGroupSection group="completed" tasks={goal.taskGroups.completed} copy={copy} defaultOpen={!archive} goalId={goal.id}/></div></section></TabsContent>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}
function WorkspaceDialogs({goal,copy,taskDialog,setTaskDialog,reviewOpen,setReviewOpen,achievementOpen,setAchievementOpen}:Props){return <><CreateTaskDialog goal={goal} copy={copy} kind="task" open={taskDialog!==null} onOpenChange={(open)=>{if(!open)setTaskDialog(null)}}/><ReviewApplyDialog goal={goal} copy={copy} open={reviewOpen} onOpenChange={setReviewOpen}/><AchievementDialog goal={goal} copy={copy} open={achievementOpen} onOpenChange={setAchievementOpen}/></>}
function setSection(props:Props,value:string){const next=new URLSearchParams(props.searchParams);if(value==="overview")next.delete("section");else next.set("section",value);props.setSearchParams(next,{replace:true})}
