"use client";
import { useMemo, useState } from "react";
import { useRevalidator } from "react-router-dom";
import { CheckCircle2 } from "lucide-react";
import { Button, Checkbox, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Field, FieldDescription, FieldLabel, Label, Textarea } from "@shared/ui";
import { runGoalAction } from "../browser-api";
import type { GoalArtifactData, GoalCopy, GoalData } from "../model/goal-types";

type DialogProps = { goal: GoalData; copy: GoalCopy; open: boolean; onOpenChange: (open: boolean) => void };
function uniqueArtifacts(goal: GoalData) { const seen = new Set<string>(); return goal.assets.flatMap((asset) => [asset.currentArtifact]).filter((artifact) => { if (seen.has(artifact.id)) return false; seen.add(artifact.id); return true; }); }
export function AchievementDialogContent({ goal, copy, open, onOpenChange }: DialogProps) {
  const revalidator = useRevalidator(); const [confirmation, setConfirmation] = useState(""); const [evidenceIds, setEvidenceIds] = useState<string[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const artifacts = useMemo(() => uniqueArtifacts(goal), [goal]);
  const submit = async () => { if (!confirmation.trim() || evidenceIds.length === 0 || pending) return; setPending(true); setError(null); try { await runGoalAction(goal.id, { action: "achieve", confirmation: confirmation.trim(), evidenceArtifactIds: evidenceIds }); await revalidator.revalidate(); onOpenChange(false); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.actionError); } finally { setPending(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{copy.confirmAchievement}</DialogTitle><DialogDescription>{copy.confirmAchievementDescription}</DialogDescription></DialogHeader><div className="space-y-5"><CriterionList goal={goal} copy={copy} /><EvidencePicker artifacts={artifacts} copy={copy} evidenceIds={evidenceIds} setEvidenceIds={setEvidenceIds} /><ConfirmationField confirmation={confirmation} setConfirmation={setConfirmation} copy={copy} />{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{copy.cancel}</Button><Button type="button" disabled={!confirmation.trim() || evidenceIds.length === 0 || pending} onClick={() => void submit()}>{pending ? copy.confirming : copy.achieve}</Button></DialogFooter></DialogContent></Dialog>;
}
function CriterionList({ goal, copy }: Pick<DialogProps, "goal" | "copy">) { return <div className="space-y-2"><p className="text-sm font-medium">{copy.successCriteria}</p>{goal.outcome.criteria.map((criterion) => <div key={criterion.id} className="flex gap-2 rounded-lg border p-3 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" />{criterion.description}</div>)}</div>; }
function EvidencePicker({ artifacts, copy, evidenceIds, setEvidenceIds }: { artifacts: GoalArtifactData[]; copy: GoalCopy; evidenceIds: string[]; setEvidenceIds: React.Dispatch<React.SetStateAction<string[]>> }) { return <Field><FieldLabel>{copy.evidenceLabel}</FieldLabel><FieldDescription>{copy.evidenceDescription}</FieldDescription><div className="space-y-2">{artifacts.map((artifact) => <Label key={artifact.id} className="flex cursor-pointer items-start gap-3 rounded-lg border p-3"><Checkbox checked={evidenceIds.includes(artifact.id)} onCheckedChange={(checked) => setEvidenceIds((current) => checked ? [...current, artifact.id] : current.filter((id) => id !== artifact.id))} /><span className="min-w-0"><span className="block text-sm font-medium">{artifact.title}</span>{artifact.contentPreview ? <span className="mt-1 block line-clamp-2 text-xs text-muted-foreground">{artifact.contentPreview}</span> : null}</span></Label>)}</div>{evidenceIds.length === 0 ? <FieldDescription className="text-destructive">{copy.evidenceRequired}</FieldDescription> : null}</Field>; }
function ConfirmationField({ confirmation, setConfirmation, copy }: { confirmation: string; setConfirmation: (value: string) => void; copy: GoalCopy }) { return <Field><FieldLabel htmlFor="goal-achievement-confirmation">{copy.confirmationLabel}</FieldLabel><Textarea id="goal-achievement-confirmation" aria-label={copy.confirmationLabel} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder={copy.confirmationPlaceholder} rows={5} /></Field>; }
