"use client";
import { useState } from "react";
import { useNavigate, useRevalidator } from "react-router-dom";
import { localizeHref, useLocale } from "@chrona/i18n";
import { Button, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Field, FieldLabel, Input, Textarea } from "@shared/ui";
import { createGoalTask } from "../browser-api";
import type { GoalCopy, GoalData } from "../model/goal-types";

type Props={goal:GoalData;copy:GoalCopy;kind:"task"|"review";open:boolean;onOpenChange:(open:boolean)=>void};
export function CreateTaskDialogContent({goal,copy,kind,open,onOpenChange}:Props){const revalidator=useRevalidator();const navigate=useNavigate();const locale=useLocale();const [expectedOutcome,setExpectedOutcome]=useState("");const [title,setTitle]=useState(kind==="review"?copy.reviewTaskTitle:"");const [description,setDescription]=useState(kind==="review"?copy.reviewTaskDescription:"");const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const submit=async()=>{if(!title.trim()||pending)return;setPending(true);setError(null);try{const {taskId}=await createGoalTask(goal.id,{title:title.trim(),description:description.trim()||undefined,kind,expectedOutcome:expectedOutcome.trim()||undefined,priority:"Medium",autoPlanGeneration:false});await revalidator.revalidate();onOpenChange(false);void navigate(localizeHref(locale,`/tasks/${taskId}`));}catch(cause){setError(cause instanceof Error?cause.message:copy.actionError)}finally{setPending(false)}};return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{copy.addTaskTitle}</DialogTitle><DialogDescription>{copy.createBoundedTaskPreview}</DialogDescription></DialogHeader><TaskFields copy={copy} title={title} setTitle={setTitle} description={description} setDescription={setDescription} expectedOutcome={expectedOutcome} setExpectedOutcome={setExpectedOutcome}/>{error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}<DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>{copy.cancel}</Button><Button type="button" disabled={!title.trim()||pending} onClick={()=>void submit()}>{pending?copy.creatingTask:copy.createTask}</Button></DialogFooter></DialogContent></Dialog>}
function TaskFields({copy,title,setTitle,description,setDescription,expectedOutcome,setExpectedOutcome}:{copy:GoalCopy;title:string;setTitle:(value:string)=>void;description:string;setDescription:(value:string)=>void;expectedOutcome:string;setExpectedOutcome:(value:string)=>void}){return <div className="space-y-4"><Field><FieldLabel htmlFor="goal-task-title">{copy.taskTitleLabel}</FieldLabel><Input id="goal-task-title" value={title} onChange={(event)=>setTitle(event.target.value)}/></Field><Field><FieldLabel htmlFor="goal-task-description">{copy.taskDescriptionLabel}</FieldLabel><Textarea id="goal-task-description" value={description} onChange={(event)=>setDescription(event.target.value)} rows={4}/></Field><Field><FieldLabel htmlFor="goal-task-expected-outcome">{copy.expectedOutcome}</FieldLabel><Textarea id="goal-task-expected-outcome" value={expectedOutcome} onChange={(event)=>setExpectedOutcome(event.target.value)} rows={3}/></Field></div>}
