"use client";
import { useState } from "react";
import { useRevalidator } from "react-router-dom";
import { CheckCircle2, CircleDot, FileText } from "lucide-react";
import { useLocale } from "@chrona/i18n";
import { Badge, Button, Checkbox, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, Field, FieldLabel, Input, Label, Textarea } from "@shared/ui";
import { confirmGoalCriterion, reviewGoalCriterion } from "../browser-api";
import type { GoalCopy, GoalData } from "../model/goal-types";
import { format, formatDate } from "./goal-workspace-shared";

export function CriteriaCardContent({ goal, copy }: { goal: GoalData; copy: GoalCopy }) {
 const locale=useLocale(); const revalidator=useRevalidator(); const [criterionId,setCriterionId]=useState<string|null>(null); const [artifactIds,setArtifactIds]=useState<string[]>([]); const [note,setNote]=useState(""); const [pending,setPending]=useState(false); const [error,setError]=useState<string|null>(null); const [proposalDraft,setProposalDraft]=useState<Record<string,string>>({}); const artifacts=goal.assets.map((asset)=>asset.currentArtifact);
 const complete=async()=>{if(!criterionId||artifactIds.length===0||!note.trim()||pending)return; setPending(true);setError(null);try{await confirmGoalCriterion(goal.id,criterionId,{artifactIds,note:note.trim()});await revalidator.revalidate();setCriterionId(null);setArtifactIds([]);setNote("");}catch(cause){setError(cause instanceof Error?cause.message:copy.actionError)}finally{setPending(false)}};
 const review=async(id:string,description:string)=>{if(pending)return;setPending(true);setError(null);try{await reviewGoalCriterion(goal.id,id,{description:proposalDraft[id]?.trim()||description});await revalidator.revalidate()}catch(cause){setError(cause instanceof Error?cause.message:copy.actionError)}finally{setPending(false)}};
 const confirmed=goal.outcome.criteria.filter((criterion)=>criterion.satisfied).length;
 return <section className="space-y-5"><CriteriaHeader copy={copy} confirmed={confirmed} total={goal.outcome.criteria.length}/><div className="divide-y rounded-xl border bg-card"><CriteriaList goal={goal} copy={copy} locale={locale} artifactsAvailable={artifacts.length>0} pending={pending} proposalDraft={proposalDraft} setProposalDraft={setProposalDraft} onReview={review} onConfirm={(id)=>{setCriterionId(id);setArtifactIds([])}}/><CriterionDialog copy={copy} artifacts={artifacts} criterionId={criterionId} artifactIds={artifactIds} setArtifactIds={setArtifactIds} note={note} setNote={setNote} pending={pending} error={error} onClose={()=>setCriterionId(null)} onSubmit={()=>void complete()}/></div></section>;
}
function CriteriaHeader({copy,confirmed,total}:{copy:GoalCopy;confirmed:number;total:number}){return <div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-muted-foreground">{copy.successCriteria}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{format(copy.criteriaProgress,{completed:confirmed,total})}</h2></div></div>}
function CriteriaList({goal,copy,locale,artifactsAvailable,pending,proposalDraft,setProposalDraft,onReview,onConfirm}:{goal:GoalData;copy:GoalCopy;locale:"en"|"zh";artifactsAvailable:boolean;pending:boolean;proposalDraft:Record<string,string>;setProposalDraft:React.Dispatch<React.SetStateAction<Record<string,string>>>;onReview:(id:string,description:string)=>Promise<void>;onConfirm:(id:string)=>void}){return <>{goal.outcome.criteria.map((criterion)=>{const proposed=criterion.proposalStatus==="proposed";return <div key={criterion.id} className={`flex flex-col gap-3 p-4 sm:flex-row sm:items-start ${criterion.satisfied?"border-l-4 border-l-success bg-success/[0.025]":proposed?"border-l-4 border-l-warning bg-warning/[0.025]":"border-l-4 border-l-muted"}`}>{criterion.satisfied?<CheckCircle2 className="mt-0.5 size-5 shrink-0 text-success" aria-hidden/>:<CircleDot className="mt-0.5 size-5 shrink-0 text-muted-foreground" aria-hidden/>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{proposed?<Badge variant="outline" className="border-warning/30 bg-warning/[0.08] text-warning">{copy.suggestedCriterion}</Badge>:null}{proposed?<Input aria-label={`Review ${criterion.description}`} value={proposalDraft[criterion.id]??criterion.description} onChange={(event)=>setProposalDraft((current)=>({...current,[criterion.id]:event.target.value}))}/>:<p className="text-sm font-medium leading-5">{criterion.description}</p>}</div><CriterionMeta criterion={criterion} copy={copy} locale={locale}/></div>{proposed&&goal.status==="Active"?<Button size="sm" disabled={pending} onClick={()=>void onReview(criterion.id,criterion.description)}>Confirm criterion</Button>:null}{!proposed&&!criterion.satisfied&&goal.status==="Active"?<Button size="sm" variant="outline" disabled={!artifactsAvailable} onClick={()=>onConfirm(criterion.id)}>{copy.confirmCriterion}</Button>:null}</div>})}</>}
function CriterionMeta({criterion,copy,locale}:{criterion:GoalData["outcome"]["criteria"][number];copy:GoalCopy;locale:"en"|"zh"}){return <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">{criterion.confirmedAt?<span className="inline-flex items-center gap-1.5"><CheckCircle2 className="size-3.5 text-success"/>{formatDate(criterion.confirmedAt,locale)}</span>:null}{(criterion.evidenceArtifactIds?.length??0)>0?<span className="inline-flex items-center gap-1.5"><FileText className="size-3.5"/>{copy.evidenceCount.replace("{count}",String(criterion.evidenceArtifactIds?.length??0))}</span>:null}</div>}
function CriterionDialog({copy,artifacts,criterionId,artifactIds,setArtifactIds,note,setNote,pending,error,onClose,onSubmit}:{copy:GoalCopy;artifacts:GoalData["assets"][number]["currentArtifact"][];criterionId:string|null;artifactIds:string[];setArtifactIds:React.Dispatch<React.SetStateAction<string[]>>;note:string;setNote:(value:string)=>void;pending:boolean;error:string|null;onClose:()=>void;onSubmit:()=>void}){return <Dialog open={criterionId!==null} onOpenChange={(open)=>{if(!open)onClose()}}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{copy.confirmCriterion}</DialogTitle><DialogDescription>{copy.confirmCriterionDescription}</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2">{artifacts.map((artifact)=><Label key={artifact.id} className="flex items-center gap-3 rounded-lg border p-3"><Checkbox checked={artifactIds.includes(artifact.id)} onCheckedChange={(checked)=>setArtifactIds((current)=>checked?[...current,artifact.id]:current.filter((id)=>id!==artifact.id))}/><span>{artifact.title}</span></Label>)}</div><Field><FieldLabel htmlFor="criterion-evidence-note">{copy.criterionEvidenceNote}</FieldLabel><Textarea id="criterion-evidence-note" value={note} onChange={(event)=>setNote(event.target.value)}/></Field>{error?<p role="alert" className="text-sm text-destructive">{error}</p>:null}</div><DialogFooter><Button variant="outline" onClick={onClose}>{copy.cancel}</Button><Button disabled={artifactIds.length===0||!note.trim()||pending} onClick={onSubmit}>{pending?copy.saving:copy.confirmCriterion}</Button></DialogFooter></DialogContent></Dialog>}
