"use client";

import { useState } from "react";
import { Check, ChevronDown, CircleOff, ExternalLink, FileText } from "lucide-react";
import { useLocale } from "@chrona/i18n";
import { Button, Card, CardContent, MarkdownContent } from "@shared/ui";
import type { GoalAcceptedResultData, GoalAssetData, GoalCopy, GoalData } from "../model/goal-types";
import { LocalizedLink } from "./localized-link";
import { artifactTypeLabel, findPrimaryResultContext, format, formatDate } from "./goal-workspace-shared";

type ArchiveContext = { result: GoalAcceptedResultData | undefined; asset: GoalAssetData | undefined } | null;
type ArchiveView = { primary: GoalData["outcome"]["primaryResult"]; context: ArchiveContext; sourceTask: GoalData["tasks"][number] | undefined; acceptedSummary: string; acceptedSummaryLead: string | undefined; retainedResultCount: number; confirmedCriteria: number; evidenceCount: number; stoppedDate: string | null };

function archiveView(goal: GoalData, locale: "en" | "zh"): ArchiveView {
  const primary = goal.outcome.primaryResult;
  const context = findPrimaryResultContext(goal, primary);
  const acceptedSummary = context?.result?.summary.trim() ?? "";
  return { primary, context, acceptedSummary, sourceTask: primary ? goal.tasks.find((task) => task.id === primary.taskId) : undefined, acceptedSummaryLead: acceptedSummary.split("\n").find((line) => line.trim())?.trim(), retainedResultCount: goal.acceptedResults.length, confirmedCriteria: goal.outcome.criteria.filter((criterion) => criterion.satisfied).length, evidenceCount: goal.outcome.confirmation?.evidenceArtifactIds.length ?? 0, stoppedDate: formatDate(goal.stoppedAt, locale) };
}

export function StoppedOutcomeArchive({ goal, copy }: { goal: GoalData; copy: GoalCopy }) {
  const locale = useLocale();
  const [resultOpen, setResultOpen] = useState(false);
  const view = archiveView(goal, locale);
  return <article className="w-full space-y-7"><StoppedHeader goal={goal} copy={copy} view={view} /><div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_18.5rem] lg:items-start"><RetainedResults goal={goal} copy={copy} locale={locale} view={view} resultOpen={resultOpen} onResultToggle={() => setResultOpen((value) => !value)} /><ArchiveSidebar goal={goal} copy={copy} view={view} /></div></article>;
}

function StoppedHeader({ goal, copy, view }: { goal: GoalData; copy: GoalCopy; view: ArchiveView }) {
  return <header className="grid gap-4 rounded-xl border border-l-4 border-l-muted-foreground bg-card p-5 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-start sm:p-6"><span className="flex size-10 items-center justify-center rounded-full bg-muted text-muted-foreground"><CircleOff className="size-5" aria-hidden /></span><div className="min-w-0"><h2 className="text-xl font-semibold tracking-tight">{copy.stoppedUnconfirmed}</h2><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{view.retainedResultCount > 0 ? format(copy.stoppedWithResultsDescription, { completed: goal.projection.completedTaskCount, results: view.retainedResultCount }) : copy.stoppedWithoutResultsDescription}</p></div><div className="text-sm text-muted-foreground sm:text-right">{view.stoppedDate ? <p>{format(copy.stoppedAt, { date: view.stoppedDate })}</p> : null}<p className="mt-1 font-medium text-foreground">{copy.stopReasonMissing}</p></div></header>;
}

function RetainedResults({ goal, copy, locale, view, resultOpen, onResultToggle }: { goal: GoalData; copy: GoalCopy; locale: "en" | "zh"; view: ArchiveView; resultOpen: boolean; onResultToggle: () => void }) {
  return <section aria-labelledby="goal-retained-results"><p className="text-xs font-medium text-muted-foreground">{copy.completedBeforeStop}</p><h2 id="goal-retained-results" className="mt-1 text-2xl font-semibold tracking-tight">{format(copy.retainedResultsCount, { count: view.retainedResultCount })}</h2><p className="mt-1 text-sm text-muted-foreground">{copy.retainedResultsDescription}</p>{view.primary ? <RetainedResultCard goal={goal} copy={copy} locale={locale} view={view} resultOpen={resultOpen} onResultToggle={onResultToggle} /> : <Card className="mt-5"><CardContent className="p-6 text-sm leading-6 text-muted-foreground">{copy.noPrimaryResult}</CardContent></Card>}</section>;
}

function RetainedResultCard({ goal, copy, locale, view, resultOpen, onResultToggle }: { goal: GoalData; copy: GoalCopy; locale: "en" | "zh"; view: ArchiveView; resultOpen: boolean; onResultToggle: () => void }) {
  const primary = view.primary!;
  return <Card className="mt-5 overflow-hidden py-0"><CardContent className="space-y-5 p-5 sm:p-6"><ResultHeading copy={copy} locale={locale} view={view} /><ResultPreview primary={primary} copy={copy} /><ResultComparison copy={copy} view={view} />{resultOpen && view.acceptedSummary ? <div className="border-t pt-4"><MarkdownContent>{view.acceptedSummary}</MarkdownContent></div> : null}<ResultActions goal={goal} copy={copy} view={view} resultOpen={resultOpen} onResultToggle={onResultToggle} /></CardContent>{view.context?.asset ? <RetainedAssetLink goal={goal} copy={copy} asset={view.context.asset} /> : null}</Card>;
}
function ResultHeading({ copy, locale, view }: { copy: GoalCopy; locale: "en" | "zh"; view: ArchiveView }) { const primary = view.primary!; return <div><p className="flex items-center gap-2 text-xs font-semibold text-success"><Check className="size-4" aria-hidden />{copy.acceptedTaskResult}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">{primary.title}</h3><p className="mt-1 text-xs text-muted-foreground">{copy.sourceTask}: {view.sourceTask?.title ?? primary.taskId}{view.context?.result?.acceptedAt ? ` · ${formatDate(view.context.result.acceptedAt, locale)}` : ""}</p></div>; }
function ResultPreview({ primary, copy }: { primary: NonNullable<GoalData["outcome"]["primaryResult"]>; copy: GoalCopy }) { return primary.contentPreview ? <div className="rounded-lg bg-success/[0.07] px-4 py-3"><p className="text-xs font-semibold text-success">{copy.outcomeSummary}</p><p className="mt-1 text-base font-semibold leading-7">{primary.contentPreview}</p></div> : null; }
function ResultComparison({ copy, view }: { copy: GoalCopy; view: ArchiveView }) { return <div className="grid gap-4 border-t pt-4 sm:grid-cols-2"><div><h4 className="text-sm font-semibold">{copy.resultCompleted}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{view.acceptedSummaryLead || view.primary?.contentPreview || copy.noPrimaryResult}</p></div><div><h4 className="text-sm font-semibold">{copy.resultDidNotConfirm}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.criterionEvidenceSummary}</p></div></div>; }
function ResultActions({ goal, copy, view, resultOpen, onResultToggle }: { goal: GoalData; copy: GoalCopy; view: ArchiveView; resultOpen: boolean; onResultToggle: () => void }) { return <div className="flex flex-col gap-2 sm:flex-row">{view.acceptedSummary ? <Button type="button" onClick={onResultToggle}>{resultOpen ? copy.hideFullResult : copy.viewFullResult}</Button> : null}{view.sourceTask ? <Button asChild type="button" variant="outline"><LocalizedLink href={`/goals/${goal.id}/workbench/tasks/${view.sourceTask.id}`}>{copy.openSourceTask}</LocalizedLink></Button> : null}</div>; }
function RetainedAssetLink({ goal, copy, asset }: { goal: GoalData; copy: GoalCopy; asset: GoalAssetData }) { return <div className="flex flex-col gap-3 border-t bg-muted/30 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg border bg-background text-success"><FileText className="size-4" aria-hidden /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{copy.retainedInWorkbench}: {asset.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{artifactTypeLabel(asset.currentArtifact.type)} · v{asset.currentVersion ?? 1}</p></div></div><Button asChild type="button" size="sm" variant="ghost"><LocalizedLink href={`/goals/${goal.id}?section=workbench&asset=${encodeURIComponent(asset.id)}`}>{copy.openAsset}<ExternalLink className="size-4" aria-hidden /></LocalizedLink></Button></div>; }

function ArchiveSidebar({ goal, copy, view }: { goal: GoalData; copy: GoalCopy; view: ArchiveView }) { return <aside className="space-y-4" aria-label={copy.archiveStatus}><ArchiveStatus goal={goal} copy={copy} view={view} /><section className="rounded-xl bg-warning/[0.09] p-5 text-sm leading-6 text-warning-foreground"><h3 className="font-semibold">{copy.whyNotAchieved}</h3><p className="mt-1 text-foreground/75">{copy.whyNotAchievedDescription}</p></section>{view.primary ? <ArchiveTechnicalDetails copy={copy} view={view} /> : null}</aside>; }
function ArchiveStatus({ goal, copy, view }: { goal: GoalData; copy: GoalCopy; view: ArchiveView }) { return <Card><CardContent className="p-5"><h3 className="font-semibold">{copy.archiveStatus}</h3><dl className="mt-4 divide-y text-sm"><ArchiveStatusRow label={copy.goalStatus} value={copy.status.Stopped} /><ArchiveStatusRow label={copy.completedTasks} value={`${goal.projection.completedTaskCount} / ${goal.projection.totalTaskCount}`} /><ArchiveStatusRow label={copy.confirmedCriteria} value={`${view.confirmedCriteria} / ${goal.outcome.criteria.length}`} tone="text-warning" /><ArchiveStatusRow label={copy.achievementEvidence} value={format(copy.achievementEvidenceCount, { count: view.evidenceCount })} tone="text-warning" /></dl></CardContent></Card>; }
function ArchiveStatusRow({ label, value, tone = "" }: { label: string; value: string; tone?: string }) { return <div className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><dt className="text-muted-foreground">{label}</dt><dd className={`font-semibold tabular-nums ${tone}`}>{value}</dd></div>; }
function ArchiveTechnicalDetails({ copy, view }: { copy: GoalCopy; view: ArchiveView }) { const primary = view.primary!; return <details className="group border-t pt-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm text-muted-foreground"><span>{copy.technicalDetails}</span><ChevronDown className="size-4 transition-transform group-open:rotate-180" /></summary><dl className="mt-4 space-y-3 text-sm"><ArchiveTechnicalRow label={copy.sourceTask} value={view.sourceTask?.title ?? primary.taskId} /><ArchiveTechnicalRow label={copy.sourceRun} value={primary.runId} mono />{view.context?.asset ? <ArchiveTechnicalRow label={copy.currentVersion} value={`v${view.context.asset.currentVersion ?? 1}`} /> : null}</dl></details>; }
function ArchiveTechnicalRow({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className={`mt-1 font-medium ${mono ? "break-all font-mono text-xs" : ""}`}>{value}</dd></div>; }
