import type { GraphCopy } from "./types";

export const AUTO_FULL_MODE_MIN_WIDTH = 760;
export const NODE_WIDTH = 198;
export const NODE_HEIGHT = 100;
export const LAYOUT_DIRECTION = "TB";
export const LAYOUT_PADDING = 32;
export const LAYOUT_NODE_SEP = 28;
export const LAYOUT_RANK_SEP = 56;
export const EDGE_OFFSET = 24;
export const MAX_VIEWPORT_HEIGHT = 620;
export const MIN_VIEWPORT_HEIGHT = 360;
export const SELECTED_NODE_Z_INDEX = 1000;

export const DEFAULT_GRAPH_COPY: GraphCopy = {
  ariaLabel: "Task plan graph",
  overviewTitle: "Execution Console",
  controlPanel: "Graph controls",
  currentNode: "Current",
  selectedNode: "Selected",
  needsAction: "Needs action",
  criticalPath: "Critical path",
  primaryPath: "Primary path",
  inactivePath: "Inactive path",
  graphStageMap: "Stage map",
  fullScreen: "Full screen",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  fitGraph: "Fit graph",
  centerCurrentNode: "Center current node",
  expandGraph: "Expand graph",
  wheelZoomHint: "Hold Ctrl/Cmd and scroll to zoom the canvas",
  openFullGraph: "Open full graph",
  compactTitle: "Flow command map",
  compactDescription: "A compressed execution map for narrow panels and mobile views.",
  fullTitle: "Full execution graph",
  fullDescription: "Inspect dependencies, current execution, and blocking actions in one control surface.",
  closeDialog: "Close full execution graph",
  overviewNodes: "Nodes",
  overviewActive: "Active",
  overviewAttention: "Attention",
  overviewDone: "Done",
  overviewEstimate: "Estimate",
  focusTitle: "Focus path",
  focusDescription: "Current, blocked, and critical nodes are prioritized.",
  inspectorTitle: "Node inspector",
  inspectorEmpty: "Select a node to inspect its goal, dependencies, and next action.",
  inspectorEmptyTitle: "No node selected",
  inspectorNextPrefix: "Next",
  inspectorGuidanceBlocked: "Resolve the blocker before continuing execution.",
  inspectorGuidanceInput: "Complete the required review or input to continue.",
  inspectorGuidanceDone: "Review the completion summary and generated evidence.",
  inspectorGuidanceActive: "Monitor this node while execution continues.",
  inspectorGuidanceDefault: "Select this node when you need to inspect its required inputs and execution context.",
  inspectorWhy: "Why It Matters",
  inspectorDependencies: "Dependencies",
  inspectorExecution: "Execution",
  inspectorOutcomes: "Outcomes",
  inspectorFields: "Interactive Fields",
  legendStates: "States",
  legendEdges: "Paths",
  detailObjective: "Objective",
  detailPhase: "Phase",
  detailExecutionMode: "Execution mode",
  detailPriority: "Priority",
  detailEstimatedDuration: "Estimated duration",
  detailLinkedTask: "Linked task",
  detailReadiness: "Readiness",
  detailNextAction: "Next action",
  detailDependencies: "Dependencies",
  detailRequiredInfo: "Required info",
  detailCompletionSummary: "Completion summary",
  detailBranches: "Branches",
  detailOptions: "Options",
  fieldRequired: "Required",
  fieldControl: "Control",
  fieldOptions: "Options",
  runFieldPlaceholderPrefix: "Enter",
  runSelectPlaceholder: "Select...",
  runApprovalOptionApprove: "Approve",
  runApprovalOptionReject: "Reject",
  runApprovalOptionNeedsChanges: "Needs changes",
  runActionSend: "Send",
  runActionApprove: "Approve",
  runActionConfirm: "Confirm",
  runActionChoose: "Choose",
  runActionSubmit: "Submit",
  runActionResolve: "Resolve",
  runActionRetry: "Retry",
  runActionObserve: "Observe",
  runActionStartPlan: "Start plan",
  runActionOpen: "Open",
  runActionMarkDone: "Mark done",
  runActionSending: "Sending...",
  runActionBackendNotice: "Actions are sent to the task execution backend.",
  runActionDefaultLabel: "Run action",
  runActionBackendMissing: "No backend handler is connected for this surface.",
  runActionDispatchFailed: "Failed to dispatch execution action",
  runActionStillRunningSuffix: "still running",
  runActionFailedSuffix: "failed",
  runActionManualCompleteFallbackPrefix: "Manual node completed",
  runActionMarkDoneFailed: "Failed to mark node done",
  runNextUiStep: "Next UI step",
  runNoFormWait: "This node is waiting on an external event, so there is no manual form to fill here.",
  runNoFormManualExecute: "Complete the manual work outside Chrona, then mark this node done here.",
  runNoFormExecute: "Execution starts from the plan entry node. This action starts or continues the plan.",
  runNoFormRetry: "This node is blocked. Use retry once the failure cause is understood.",
  runNoFormDefault: "This node does not require free-form input. The action here is a direct decision or execution step.",
  runResultTitle: "Run result",
  runResultEmpty: "No run result yet for this node.",
  runEvidenceTitle: "Evidence",
  runFeedTitle: "Run feed",
  runFeedEmptyWithControls: "Select a node action, fill required fields, then send it to the execution backend.",
  runFeedEmptyWithoutControls: "Run controls appear only for the current node. Results for this node still show here.",
  runOutputJsonTitle: "JSON",
  runOutputFileTitle: "File output",
  runOutputArtifactPrefix: "Artifact",
  runOutputCommandTitle: "Command",
  runOutputExitPrefix: "exit",
  runPanelExecuteEyebrow: "Execution panel",
  runPanelExecuteTitle: "Ready to execute",
  runPanelExecuteDescription: "Execution starts from the plan entry node. This action starts or continues the plan.",
  runPanelConfirmEyebrow: "Confirmation panel",
  runPanelConfirmTitle: "Waiting for confirmation",
  runPanelConfirmDescription: "This node needs a clear confirmation before the run can proceed.",
  runPanelChooseEyebrow: "Decision panel",
  runPanelChooseTitle: "Waiting for a choice",
  runPanelChooseDescription: "Select the branch or decision needed to continue this plan.",
  runPanelInputEyebrow: "Input panel",
  runPanelInputTitle: "Waiting for user input",
  runPanelInputDescription: "This node is paused until the required input is submitted.",
  runPanelEditEyebrow: "Edit panel",
  runPanelEditTitle: "Waiting for edits",
  runPanelEditDescription: "This node expects a structured revision before execution can continue.",
  runPanelApproveEyebrow: "Approval panel",
  runPanelApproveTitle: "Waiting for approval",
  runPanelApproveDescription: "This node needs an explicit approval decision before execution can continue.",
  runPanelWaitEyebrow: "Wait panel",
  runPanelWaitTitle: "Waiting on an external event",
  runPanelWaitDescription: "This node is paused by design until its wait condition is satisfied.",
  runPanelRetryEyebrow: "Retry panel",
  runPanelRetryTitle: "Node needs recovery",
  runPanelRetryDescription: "This node is blocked. Capture the retry rationale and restart from here.",
  runPanelObserveEyebrow: "Observe panel",
  runPanelObserveTitle: "Current run focus",
  runPanelObserveDescription: "Use this surface to monitor the active node and advance the run when ready.",
  runHintExecuteReview: "Review dependencies and objective.",
  runHintExecuteEntry: "Execution starts from the plan entry node, not from an arbitrary selected node.",
  runHintConfirmReview: "Read the checkpoint summary carefully.",
  runHintConfirmPrereq: "Confirm only when the prerequisite condition is truly satisfied.",
  runHintChoosePick: "Pick one branch or decision path.",
  runHintChooseDownstream: "The selected option determines downstream execution.",
  runHintInputFill: "Fill in the required fields.",
  runHintInputContext: "Submitted input becomes the runtime context for the next step.",
  runHintEditRevise: "Revise the requested content before continuing.",
  runHintEditCheckpoint: "Treat this as a correction checkpoint, not a new task step.",
  runHintApproveGate: "This is a sign-off gate for a sensitive operation.",
  runHintApproveIntent: "Approval here should represent explicit intent, not just observation.",
  runHintRetryCause: "Capture why the node needs another attempt.",
  runHintRetryUse: "Use retry only after the blocking cause is understood.",
  runHintWaitManual: "No manual action is needed yet.",
  runHintWaitMonitor: "Monitor the wait condition and related downstream context.",
  runHintObserveContext: "Use this panel to inspect the live node context.",
  runHintObserveAdvance: "Advance the run only when the current state is clear.",
  statusIdle: "Idle",
  statusReady: "Ready",
  statusActive: "Active",
  statusWaiting: "Waiting",
  statusBlocked: "Blocked",
  statusDone: "Done",
  statusSkipped: "Skipped",
  edgeSequential: "Sequential",
  edgeDependency: "Dependency",
  edgeBranch: "Branch",
  edgeResume: "Resume",
  nodeTypeTask: "Task",
  nodeTypeCheckpoint: "Checkpoint",
  nodeTypeCondition: "Condition",
  nodeTypeWait: "Wait",
  intentExecution: "Execution",
  intentApproval: "Approval",
  intentInput: "Input",
  intentDecision: "Decision",
  intentPause: "Pause",
};
