import type { GraphCopy } from "./types";

export const AUTO_FULL_MODE_MIN_WIDTH = 760;
export const NODE_WIDTH = 198;
export const NODE_HEIGHT = 100;
export const LAYOUT_DIRECTION = "TB";
export const LAYOUT_PADDING = 32;
export const LAYOUT_NODE_SEP = 28;
export const LAYOUT_RANK_SEP = 56;
export const EDGE_OFFSET = 24;
export const MAX_VIEWPORT_HEIGHT = 620;
export const MIN_VIEWPORT_HEIGHT = 360;
export const SELECTED_NODE_Z_INDEX = 1000;

export const DEFAULT_GRAPH_COPY: GraphCopy = {
  ariaLabel: "Task plan graph",
  overviewTitle: "Execution Console",
  controlPanel: "Graph controls",
  currentNode: "Current",
  selectedNode: "Selected",
  needsAction: "Needs action",
  criticalPath: "Critical path",
  primaryPath: "Primary path",
  inactivePath: "Inactive path",
  graphStageMap: "Stage map",
  fullScreen: "Full screen",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  fitGraph: "Fit graph",
  centerCurrentNode: "Center current node",
  expandGraph: "Expand graph",
  wheelZoomHint: "Hold Ctrl/Cmd and scroll to zoom the canvas",
  openFullGraph: "Open full graph",
  compactTitle: "Flow command map",
  compactDescription: "A compressed execution map for narrow panels and mobile views.",
  fullTitle: "Full execution graph",
  fullDescription: "Inspect dependencies, current execution, and blocking actions in one control surface.",
  closeDialog: "Close full execution graph",
  overviewNodes: "Nodes",
  overviewActive: "Active",
  overviewAttention: "Attention",
  overviewDone: "Done",
  overviewEstimate: "Estimate",
  focusTitle: "Focus path",
  focusDescription: "Current, blocked, and critical nodes are prioritized.",
  inspectorTitle: "Node inspector",
  inspectorEmpty: "Select a node to inspect its goal, dependencies, and next action.",
  inspectorWhy: "Why It Matters",
  inspectorDependencies: "Dependencies",
  inspectorExecution: "Execution",
  inspectorOutcomes: "Outcomes",
  inspectorFields: "Interactive Fields",
  legendStates: "States",
  legendEdges: "Paths",
  detailObjective: "Objective",
  detailPhase: "Phase",
  detailExecutionMode: "Execution mode",
  detailPriority: "Priority",
  detailEstimatedDuration: "Estimated duration",
  detailLinkedTask: "Linked task",
  detailReadiness: "Readiness",
  detailNextAction: "Next action",
  detailDependencies: "Dependencies",
  detailRequiredInfo: "Required info",
  detailCompletionSummary: "Completion summary",
  statusIdle: "Idle",
  statusReady: "Ready",
  statusActive: "Active",
  statusWaiting: "Waiting",
  statusBlocked: "Blocked",
  statusDone: "Done",
  statusSkipped: "Skipped",
  edgeSequential: "Sequential",
  edgeDependency: "Dependency",
  edgeBranch: "Branch",
  edgeResume: "Resume",
  nodeTypeTask: "Task",
  nodeTypeCheckpoint: "Checkpoint",
  nodeTypeCondition: "Condition",
  nodeTypeWait: "Wait",
  intentExecution: "Execution",
  intentApproval: "Approval",
  intentInput: "Input",
  intentDecision: "Decision",
  intentPause: "Pause",
};
