// Markdown rendering for the feature+test map.
// Pure functions: MapModel -> markdown string. No IO.
import path from "node:path";
import { MAX_DEPTH, WORKFLOWS, isTestableKind, type FileEntry, type MapModel } from "./feature-test-map-model";

function pct(n: number, d: number): string {
  return d === 0 ? "0%" : `${Math.round((100 * n) / d)}%`;
}

function groupByWorkflow(files: FileEntry[]): Map<string, FileEntry[]> {
  const byWf = new Map<string, FileEntry[]>();
  for (const f of files) {
    if (!byWf.has(f.workflow)) byWf.set(f.workflow, []);
    byWf.get(f.workflow)!.push(f);
  }
  return byWf;
}

const WF_ORDER = [...WORKFLOWS.map((w) => w.id), "unmapped"];
const WF_TITLE = new Map<string, string>([
  ...WORKFLOWS.map((w) => [w.id, w.title] as const),
  ["unmapped", "Unmapped (no workflow bucket)"],
]);

function renderHeader(t: MapModel["totals"]): string[] {
  return [
    "# Chrona Feature + Test Map",
    "",
    "> Generated by `scripts/build-feature-test-map.ts`. Do not edit by hand.",
    "> Regenerate with `bun run map:build`.",
    "",
    "Drill-down: product workflow -> package -> module -> source file, annotated with covering tests.",
    "",
    "**Coverage signals (distinct):**",
    "",
    "- **direct** = a test statically imports the file (`import`/`require`/`vi.mock`).",
    `- **transitive** = a test reaches the file through the source import graph (bounded BFS, depth ${MAX_DEPTH}).`,
    "- **symbol-level** = a directly-importing test references the exported symbol by name (structural, not runtime).",
    "- direct is the conservative truth; transitive shows what a test pulls in. Neither is runtime line coverage (see note at end).",
    "",
    "## Totals",
    "",
    "| Metric | Value |",
    "| --- | --- |",
    `| Source files | ${t.sourceFiles} |`,
    `| Test files | ${t.testFiles} |`,
    `| Directly covered files | ${t.directCovered} (${pct(t.directCovered, t.sourceFiles)}) |`,
    `| Transitively covered files | ${t.transitiveCovered} (${pct(t.transitiveCovered, t.sourceFiles)}) |`,
    `| Uncovered files (no test reaches) | ${t.uncovered} (${pct(t.uncovered, t.sourceFiles)}) |`,
    `| Exported symbols | ${t.exportedSymbols} |`,
    `| Symbols referenced by a direct test | ${t.symbolsWithTest} (${pct(t.symbolsWithTest, t.exportedSymbols)}) |`,
    "",
  ];
}

function renderWorkflowSummary(byWf: Map<string, FileEntry[]>): string[] {
  const L = ["## Workflow coverage summary", "", "| Workflow | Files | Direct | Transitive | Uncovered |", "| --- | --- | --- | --- | --- |"];
  for (const wf of WF_ORDER) {
    const fl = byWf.get(wf);
    if (!fl || fl.length === 0) continue;
    const dc = fl.filter((f) => f.directTests.length > 0).length;
    const tc = fl.filter((f) => f.transitiveTests.length > 0).length;
    L.push(`| ${WF_TITLE.get(wf)} | ${fl.length} | ${dc} (${pct(dc, fl.length)}) | ${tc} (${pct(tc, fl.length)}) | ${fl.length - tc} |`);
  }
  L.push("");
  return L;
}

function renderTestNames(f: FileEntry): string {
  if (f.directTests.length > 0) return f.directTests.map((t) => `\`${path.basename(t)}\``).join("<br>");
  if (f.transitiveTests.length > 0) return "_(transitive only)_";
  return "**none**";
}

function renderSymbolDetail(f: FileEntry): string[] {
  // only the testable (function/class/const) symbols are interesting at function level
  const testable = f.symbols.filter((s) => isTestableKind(s.kind));
  if (testable.length === 0) return [];
  const L = [`<details><summary><code>${f.file}</code> &mdash; ${testable.length} exported symbol(s)</summary>`, "", "| Symbol | Kind | Tests referencing it |", "| --- | --- | --- |"];
  for (const s of testable) {
    const tests = s.tests.length > 0 ? s.tests.map((t) => `\`${path.basename(t)}\``).join("<br>") : "**none**";
    L.push(`| \`${s.name}\` | ${s.kind} | ${tests} |`);
  }
  L.push("", "</details>", "");
  return L;
}

function renderBucket(key: string, files: FileEntry[]): string[] {
  const sorted = [...files].sort((a, b) => a.file.localeCompare(b.file));
  const dc = sorted.filter((f) => f.directTests.length > 0).length;
  const L = [
    `#### ${key}  _(${sorted.length} files, ${dc} direct-covered)_`,
    "",
    "| Source file | Direct | Transitive | Symbols (tested/total) | Test names |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const f of sorted) {
    const testable = f.symbols.filter((s) => isTestableKind(s.kind));
    const tested = testable.filter((s) => s.tests.length > 0).length;
    const symCol = testable.length > 0 ? `${tested}/${testable.length}` : "&mdash;";
    L.push(`| \`${f.file}\` | ${f.directTests.length} | ${f.transitiveTests.length} | ${symCol} | ${renderTestNames(f)} |`);
  }
  L.push("");
  // per-file symbol detail for files that have directly-importing tests (signal worth drilling)
  for (const f of sorted) {
    if (f.directTests.length > 0) L.push(...renderSymbolDetail(f));
  }
  return L;
}

function renderDrilldown(byWf: Map<string, FileEntry[]>): string[] {
  const L = ["## Drill-down", ""];
  for (const wf of WF_ORDER) {
    const fl = byWf.get(wf);
    if (!fl || fl.length === 0) continue;
    L.push(`### ${WF_TITLE.get(wf)}`, "");
    const byKey = new Map<string, FileEntry[]>();
    for (const f of fl) {
      const k = `${f.pkg} :: ${f.module}`;
      if (!byKey.has(k)) byKey.set(k, []);
      byKey.get(k)!.push(f);
    }
    for (const k of [...byKey.keys()].sort()) L.push(...renderBucket(k, byKey.get(k)!));
  }
  return L;
}

function renderUncovered(files: FileEntry[]): string[] {
  const uncovered = files.filter((f) => f.transitiveTests.length === 0);
  const L = [
    "## Uncovered source files",
    "",
    "Files no test reaches even transitively. Entry points (`index`, `bootstrap`, route wiring) and scripts are expected here; product logic is not.",
    "",
  ];
  if (uncovered.length === 0) {
    L.push("_None._");
  } else {
    L.push("| Source file | Bucket |", "| --- | --- |");
    for (const f of uncovered) L.push(`| \`${f.file}\` | ${f.pkg} :: ${f.module} |`);
  }
  L.push("");
  return L;
}

function renderMethodologyNote(): string[] {
  return [
    "## Methodology & limits",
    "",
    "This map is **structural**, derived from the import graph + TypeScript AST, not runtime instrumentation:",
    "",
    "- **direct / transitive** edges come from resolving every `import`/`require`/`vi.mock`/dynamic-`import()` specifier in each test against `tsconfig.json` path aliases, then walking the source import graph (BFS, depth " + MAX_DEPTH + ").",
    "- **symbol-level** marks an export as covered when a directly-importing test references its name; a test that imports a file but never names a given export leaves that export `none`. Mocked-out symbols still count as referenced (they appear in `vi.mock`/call sites).",
    "- Re-export-only barrels (`export * from`) show as files with transitive coverage and no own symbols; that is expected.",
    "",
    "What this map does **not** prove: runtime line/branch execution. Empirical coverage is a separate axis and is intentionally not merged here, because Chrona runs two disjoint test runners (Bun `*.bun.test.ts` and Vitest `*.test.ts(x)`) whose v8 coverage cannot be unified into one deterministic number. For empirical line coverage run `bunx vitest run --coverage` (Vitest/jsdom slice) and `bun test --coverage` (Bun slice) separately; this map answers \"what is tested and by which test\", the coverage runs answer \"how thoroughly\".",
    "",
  ];
}

export function renderMarkdown(model: MapModel): string {
  const byWf = groupByWorkflow(model.files);
  return [
    ...renderHeader(model.totals),
    ...renderWorkflowSummary(byWf),
    ...renderDrilldown(byWf),
    ...renderUncovered(model.files),
    ...renderMethodologyNote(),
  ].join("\n");
}
