export const TIMELINE_SLOT_MINUTES = 30;
export const DEFAULT_SCHEDULE_BLOCK_MINUTES = 60;
export const TIMELINE_COMPOSER_HEIGHT = 356;
export const TIMELINE_COMPOSER_MARGIN = 12;

export const DEFAULT_SCHEDULE_PAGE_COPY = {
  planPrefix: "Plan",
  runPrefix: "Run",
  approvalsPrefix: "Approvals",
  blockSingular: "block",
  blockPlural: "blocks",
  proposalSingular: "proposal",
  proposalPlural: "proposals",
  noScheduledStart: "No scheduled start",
  agentAssigned: "Agent-assigned",
  agentPrefix: "Agent",
  humanOwned: "Human-owned",
  timeNotSet: "Time not set",
  unscheduled: "Unscheduled",
  dayOpenSuffix: "is open for new blocks",
  riskDay: "Risk day",
  createTaskBlock: "Create Task Block",
  cancel: "Cancel",
  createAndSchedule: "Create and schedule",
  creating: "Creating…",
  quickCreateTitleLabel: "Title",
  quickCreateTitlePlaceholder: "What needs to happen?",
  quickCreateQueueTitlePlaceholder: "Add a task to the queue",
  quickCreateStartLabel: "Start",
  quickCreateStartNowLabel: "Now",
  quickCreateStartMorningLabel: "Morning",
  quickCreateStartAfternoonLabel: "Afternoon",
  quickCreateStartEveningLabel: "Evening",
  quickCreateDurationLabel: "Duration",
  quickCreateDurationMinutesLabel: "min",
  quickCreateDurationHoursLabel: "hours",
  quickCreatePriorityLabel: "Priority",
  quickCreateQueueSubmit: "Add to queue",
  quickCreateQueueHint:
    "Create a lightweight task first, then drag it onto the timeline when you are ready to place it.",
  dropOntoLane: "Drop work onto the lane",
  clickOrDrag: "Click any slot or drag to adjust",
  timelineCompressedPrefix: "Timeline compressed: 24h shown as",
  emptyDayLane: "Empty day lane",
  emptyDayLaneDescription:
    "Drop a queued task anywhere on this lane to create the first block.",
  dropToSchedule: "Drop to schedule",
  dropToMoveBlock: "Drop to move block",
  overdue: "Overdue",
  approvalPending: "Approval pending",
  conflictPreviewLabel: "Conflict — resolve overlap before committing this block.",
  resizePreviewLabel: "Resize block",
  adjustBlock: "Adjust block",
  resizeHandleLabel: "Resize",
  quickCreatePlaceholder: "Task title, @ 14:30, for 90m, !high",
  quickCreateSubmit: "Add block",
  quickCreateHint:
    "Examples: 'Write weekly report @ 14:30 for 90m !high' or just type a title for the next open slot.",
  closeTaskDetails: "Close task details",
  taskDetails: "Task Details",
  taskDetailsDescription:
    "Review the selected block in a floating panel, then return to the timeline.",
  taskDetailsEyebrow: "Task cockpit",
  close: "Close",
  due: "Due",
  currentPlan: "Current plan",
  latestRun: "Latest run",
  nextAction: "Next action",
  noActiveRun: "No active run",
  stayOnPlan: "Stay on plan",
  taskConfig: "Task config",
  saveTaskConfig: "Save task config",
  saving: "Saving…",
  scheduledWindow: "Scheduled window",
  placeOnTimeline: "Place on timeline",
  scheduleTask: "Schedule Task",
  schedulingUpdating: "Scheduling is updating.",
  dragHint:
    "Drag to the timeline or expand for details and fallback scheduling.",
  pendingProposals: "Pending proposals",
  runnable: "Runnable",
  model: "Model",
  proposedBy: "Proposed by",
  candidateBlock: "Candidate block",
  dueImpact: "Due impact",
  source: "Source",
  acceptProposal: "Accept Proposal",
  rejectProposal: "Reject Proposal",
  risk: "Risk",
  action: "Action",
  needsReview: "Needs review",
  reviewScheduleImpact: "Review schedule impact",
  plannedWindow: "Planned window",
  openInbox: "Open Inbox",
  pageTitle: "Schedule",
  cockpitSummary:
    "See today’s load, what is still waiting, and where the next decision should happen.",
  cockpitTodayLoad: "Today load",
  cockpitTodayLoadHint: "Committed work on the active day.",
  cockpitQueueHint: "Tasks that are ready to be placed next.",
  cockpitRisksHint: "Items that need review before the plan feels safe.",
  cockpitSuggestions: "AI suggestions",
  cockpitSuggestionsHint: "Automation and proposal opportunities waiting for review.",
  automationTitle: "Automation",
  automationDescription: "Backend-capable execution and scheduling actions.",
  automationEmpty: "No automation candidates right now.",
  automationRunNow: "Run now",
  automationUnsupportedRuntime: "This runtime cannot be auto-executed from Chrona.",
  automationBackendOnlyHint: "Chrona only sends execution requests to backend-managed runtimes such as OpenClaw.",
  cockpitReviewSuggestions: "Review suggestions",
  cockpitReviewSuggestionsHint: "Open the cockpit sidebar and triage the queue.",
  cockpitAutoArrange: "Auto arrange",
  cockpitAutoArrangeHint: "Coming soon · preview the future planning action.",
  cockpitPlanWithAi: "Plan with AI",
  cockpitPlanWithAiHint: "Coming soon · AI-assisted schedule shaping.",
  cockpitSummaryTemplate:
    "{scheduled} scheduled · {queue} queued next · {risks} risks to review · {automation} automation candidates",
  cockpitViewsLabel: "Views",
  cockpitActionsLabel: "Actions",
  today: "Today",
  tomorrow: "Tomorrow",
  currentPlanButton: "Current Plan",
  timeline: "Timeline",
  list: "List",
  scheduledMetric: "Scheduled",
  scheduledMetricHint: "Committed blocks on the current plan.",
  queueMetric: "Queue",
  queueMetricHint: "Tasks still waiting to enter the timeline.",
  aiProposalsMetric: "AI Proposals",
  aiProposalsMetricHint: "Pending suggestions that need a decision.",
  risksMetric: "Risks",
  risksMetricHint: "At-risk, overdue, or interrupted work.",
  scheduledTimeline: "Scheduled Timeline",
  scheduledTimelineDescription: "",
  dropMode: "Drop mode",
  planningSurface: "Planning surface",
  conflictsTitle: "Conflicts / Overdue Risks",
  conflictsDescription: "",
  conflictDetectionTitle: "AI Conflict Detection",
  conflictDetectionEmpty: "No conflicts detected.",
  noScheduleRisks:
    "No schedule risks detected. Blocked, overdue, or interrupted work will surface here.",
  aiProposalsTitle: "AI Proposals",
  aiProposalsDescription: "",
  noAiProposals:
    "No pending AI proposals. When planner automation suggests a new block, it will appear here for review.",
  openTaskCenter: "Open Task Center",
  weekOverview: "Week Overview",
  noTimelineDay: "No timeline day is available right now.",
  unscheduledQueue: "Unscheduled Queue",
  unscheduledQueueDescription:
    "Collapsed task cards stay in the side rail. Expand only when needed, or drag them directly into the timeline.",
  noUnscheduledWork:
    "No unscheduled work. New tasks that lose their plan or need initial placement will appear here.",
  dateSwitcher: "Date",
  todayFocus: "Today Focus",
  todayFocusEmpty:
    "Nothing urgent is blocking today. Use the queue to place the next meaningful block.",
  focusOverdue: "Overdue",
  focusAtRisk: "At risk",
  focusWaitingForInput: "Waiting for input",
  focusWaitingForApproval: "Waiting for approval",
  focusReadyToday: "Ready to start today",
  todayBlocks: "Today blocks",
  queueReady: "Queue ready",
  needsAttention: "Needs attention",
  aiProposalsCompactEmpty: "No pending AI proposals.",
  taskPlanLabel: "Task Plan",
  loadingTaskPlan: "Loading task plan…",
  childTasksLabel: "Child Tasks",
  childTaskReopen: "Reopen",
  childTaskMarkDone: "Mark done",
} as const;

export type SchedulePageCopy = Record<
  keyof typeof DEFAULT_SCHEDULE_PAGE_COPY,
  string
>;

export function getSchedulePageCopy(
  messages?: Partial<SchedulePageCopy> | null,
): SchedulePageCopy {
  return {
    ...DEFAULT_SCHEDULE_PAGE_COPY,
    ...(messages ?? {}),
  };
}

